End to end tomography
sfc-aqua/quisp pull request #205
Opened 2021-06-08 07:01 UTC by Chibikuri

# End to end tomography for entanglement swapping
## What I did
- Fixed bug on the qnic specification when the responder creates swapping rulesets.
- Modified RandomMeasureAction in Action.cc to deal with multihop entanglements.
- Modified HardwareMonitor.cc to print out the result.

## What to do before merging. 
- [ ] Check the result is correct numerically
- [ ] Add some end-to-end tests to verify the result.
- [ ] Add tests to check each module.

2021-06-24 06:33 UTC, Chibikuri commented
I have tested that module test works. 
The commits are messy, so I tried to cherry-pick them. However, the commit history was so complex and it returns a lot of errors after resolving conflicts. 
So I would like to merge this branch with some documentations.

2021-06-24 07:08 UTC, zigen requested changes
it's a big PR, so I reviewed only related to coding style for several files.
later I'll check it works and review the substantial parts.

2021-06-24 07:08 UTC, zigen commented on quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc
> +  EV << "qubit allocated"
make it one line. for debug purposes, use `EV_DEBUG` or remove it.

2021-06-24 07:08 UTC, zigen commented on quisp/modules/QNode.ned
> +                //@display("p=232,173");
remove it

2021-06-24 07:08 UTC, zigen commented on quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc
> +    // This is a classical pakcet for connection setup request
really do we need this comment?

2021-06-24 07:08 UTC, zigen commented on quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc
> +      EV << link_left[i] << "---------------" << swapper[i] << "----------------" << link_right[i] << "\n";
it's same as next line

2021-06-24 07:08 UTC, zigen commented on quisp/modules/QRSA/RuleEngine/RuleEngine_test.cc
> +// TEST(RuleEngineTest, Init) {
remove it

2021-06-24 07:11 UTC, Chibikuri commented on quisp/Makefile
> +#
Got it. I'll remove it.

2021-06-24 07:13 UTC, Chibikuri commented on quisp/modules/Application/Application.ned
> +        int NumMeasureApp=default(7000);
Ah, yeah. But there is a variable `num_measure`, and it would be confusing when they are the same .ini file?

2021-06-24 07:13 UTC, Chibikuri commented on quisp/modules/Common/Router.cc
> +  // EV << "forwarding packet " << pk->getName() << " on gate index " << outGateIndex << endl;
Oh, yeah.

2021-06-24 07:17 UTC, Chibikuri commented on quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc
> +    // This is a classical pakcet for connection setup request
We don't need that.

2021-06-24 07:17 UTC, Chibikuri commented on quisp/modules/QRSA/ConnectionManager/ConnectionManager.cc
> +    // This is a classical pakcet for connection setup request
Will remove it

2021-06-24 07:19 UTC, Chibikuri commented
OK, I cleaned up them.

2021-06-24 07:23 UTC, zigen commented on quisp/modules/Application/Application.ned
> +        int NumMeasureApp=default(7000);
you already deleted the variable `num_measure` in Application.ned`. are you talking about other module's `num_measure` var?

2021-06-25 05:34 UTC, zigen commented
hmm, this PR still contains ABSA and RGS related code so it's too hard to review...

2021-06-25 05:35 UTC, Chibikuri commented
OK, let me try to clean up them first.

2021-06-25 05:37 UTC, zigen commented
or tell me which the exact commits are for this PR. I'll try to cherry-pick

2021-06-25 05:47 UTC, Chibikuri commented
The commits directly related to this PR is from ae3061ad1c4d1b1cc8123498d71e13774c859e5a to 7f50d807758817885b339138bbea805a67299d9c.

2021-06-25 13:15 UTC, Chibikuri commented
Let me close this and reopen with cleaned branch

2021-06-25 13:15 UTC, closed without merging