Fix Measurement Error and add new function for measurement
sfc-aqua/quisp pull request #351
Opened 2022-01-20 08:57 UTC by Naphann

I added new functions called "local_measurement" which can only be used with Bell pair when we want the eigenvalues to determine the next operation e.g., entanglement swapping.

This should fix #337 #343

2022-01-20 11:21 UTC, zigen requested changes
> Reviewed 2 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/351)* status: 2 of 12 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h, line 92 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/351#-MtrBXFo0KlgPcBWwBib:-MtrBXFp8VwcN1rFatQ0:b-r421ug) ([raw file](https://github.com/sfc-aqua/quisp/blob/5bc75d5fd81994b7eda031c0d51ffeda99133092/quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h#L92)):*
> ```objc
>   double X_measurement_error_rate;
>   double Y_measurement_error_rate;
>   double Z_measurement_error_rate;
> ```

could you rename fields to snake_case? e.g. `double x_measurement_error_rate`
I'd like to check the names automatically with clang-tidy later, but clang-tidy cannot handle 
 the mixed case like`X_mesurement_error_rate`.
___
*[quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h, line 92 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/351#-MtrC6Q21U7WMCOHlWCc:-MtrC6Q21U7WMCOHlWCd:b-1gevt7) ([raw file](https://github.com/sfc-aqua/quisp/blob/5bc75d5fd81994b7eda031c0d51ffeda99133092/quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h#L92)):*
> ```objc
>   double X_measurement_error_rate;
>   double Y_measurement_error_rate;
>   double Z_measurement_error_rate;
> ```

how about removing `_measurement` from `X_measurement_error_rate`. 
Because we already know that the struct describes the measurement error, so `_measurement` part seems too redundant.
for me, `x_error_rate` is enough informative.


<!-- Sent from Reviewable.io -->

2022-01-21 02:47 UTC, Chibikuri requested changes
> Reviewed 3 of 12 files at r1, 7 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/351)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @Chibikuri, @Naphann, and @zigen)

___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned, line 127 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/351#-MtuVUr-6Huweu2F6wm6:-MtuVUr-6Huweu2F6wm7:b-wy2ps6) ([raw file](https://github.com/sfc-aqua/quisp/blob/bd22c78ae0ef918784aff49fd2d1c9cbbc1f930b/quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned#L127)):*
> ```
>         //int rule_id = default(-1);
>         //int action_index = default(-1);
>         gates:
> ```

Did you intend to remove indentation?


<!-- Sent from Reviewable.io -->

2022-01-21 02:50 UTC, Naphann reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/351)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @Chibikuri, @Naphann, and @zigen)

___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned, line 127 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/351#-MtuVUr-6Huweu2F6wm6:-MtuXRpF4iHwgzqLHhxo:bwmtyi) ([raw file](https://github.com/sfc-aqua/quisp/blob/bd22c78ae0ef918784aff49fd2d1c9cbbc1f930b/quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned#L127)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh) wrote…</i></summary><blockquote>

Did you intend to remove indentation?
</blockquote></details>

Ah, probably my formatter or something I did. Will fix it


<!-- Sent from Reviewable.io -->

2022-01-22 02:14 UTC, zigen requested changes
> Reviewed 3 of 12 files at r1, 6 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/351)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.h, line 68 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/351#-MtzY7Vv74AbpRrFXZfe:-MtzY7Vv74AbpRrFXZff:b-e0dgc3) ([raw file](https://github.com/sfc-aqua/quisp/blob/5bc75d5fd81994b7eda031c0d51ffeda99133092/quisp/modules/QNIC/StationaryQubit/StationaryQubit.h#L68)):*
> ```objc
>   virtual types::EigenvalueResult local_measure_X() override;
>   virtual types::EigenvalueResult local_measure_Y() override;
>   virtual types::EigenvalueResult local_measure_Z() override;
> ```

could you change the method names to snake case? like `local_measure_x`
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned, line 127 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/351#-MtuVUr-6Huweu2F6wm6:-MtzYTFT4t5ouu4IJBgc:b-kqcso5) ([raw file](https://github.com/sfc-aqua/quisp/blob/bd22c78ae0ef918784aff49fd2d1c9cbbc1f930b/quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned#L127)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Ah, probably my formatter or something I did. Will fix it
</blockquote></details>

OMNeT++ IDE can format this


<!-- Sent from Reviewable.io -->

2022-01-22 02:16 UTC, zigen requested changes
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/351)* status: all files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.h, line 68 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/351#-MtzY7Vv74AbpRrFXZfe:-MtzZDADBESFJIpyXhxO:b-iae3dw) ([raw file](https://github.com/sfc-aqua/quisp/blob/5bc75d5fd81994b7eda031c0d51ffeda99133092/quisp/modules/QNIC/StationaryQubit/StationaryQubit.h#L68)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

could you change the method names to snake case? like `local_measure_x`
</blockquote></details>

no, the method name should be capitalCase, so it should be `localMeasureX()`


<!-- Sent from Reviewable.io -->

2022-01-22 05:23 UTC, Naphann reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/351)* status: 3 of 12 files reviewed, 2 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h, line 92 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/351#-MtrBXFo0KlgPcBWwBib:-Mu-Cnce6Eoyl0naeSWP:b-t3m7pj) ([raw file](https://github.com/sfc-aqua/quisp/blob/5bc75d5fd81994b7eda031c0d51ffeda99133092/quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h#L92)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

could you rename fields to snake_case? e.g. `double x_measurement_error_rate`
I'd like to check the names automatically with clang-tidy later, but clang-tidy cannot handle 
 the mixed case like`X_mesurement_error_rate`.
</blockquote></details>

changed according to the comments
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.h, line 68 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/351#-MtzY7Vv74AbpRrFXZfe:-Mu-CrIABwwhVVEffz7f:b-mwiqbo) ([raw file](https://github.com/sfc-aqua/quisp/blob/5bc75d5fd81994b7eda031c0d51ffeda99133092/quisp/modules/QNIC/StationaryQubit/StationaryQubit.h#L68)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

no, the method name should be capitalCase, so it should be `localMeasureX()`
</blockquote></details>

Changed to camelCase.
___
*[quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned, line 127 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/351#-MtuVUr-6Huweu2F6wm6:-Mu-Cv6P8_ffbhnXBlsX:blnog2p) ([raw file](https://github.com/sfc-aqua/quisp/blob/bd22c78ae0ef918784aff49fd2d1c9cbbc1f930b/quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned#L127)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

OMNeT++ IDE can format this
</blockquote></details>

formatted via OMNeT IDE (although IDE would also remove the indent of 3 comments line above I added the indent to them to stay the same)


<!-- Sent from Reviewable.io -->

2022-01-24 05:52 UTC, zigen approved these changes
> Reviewed 1 of 8 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/351)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri)



<!-- Sent from Reviewable.io -->

2022-01-24 05:52 UTC, zigen approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/351#-:-Mu9d97a9dslDSeEX1YC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri)



<!-- Sent from Reviewable.io -->

2022-01-24 07:54 UTC, Chibikuri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/351#-:-MuA45AVCnvKLkkA1Gin:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Chibikuri)



<!-- Sent from Reviewable.io -->

2022-01-24 08:00 UTC, Naphann reviewed
> Dismissed @Chibikuri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/351)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Naphann)



<!-- Sent from Reviewable.io -->

2022-01-24 08:01 UTC, merged

2022-01-24 08:03 UTC, Naphann commented
this fixed #337 and fixed #343