RuleEngine Runtime
sfc-aqua/quisp pull request #431
Opened 2022-09-24 12:51 UTC by zigen

just an experimental implementation

2022-09-26 08:42 UTC, Chibikuri reviewed
> Reviewed 3 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/431)* status: 3 of 16 files reviewed, all discussions resolved (waiting on @Chibikuri)



<!-- Sent from Reviewable.io -->

2022-09-28 01:01 UTC, Chibikuri requested changes
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/431)* status: 3 of 16 files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @zigen)

___
*[`quisp/runtime/def_instructions.h` line 32 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/431#-ND0apsuCSjLtgWwk-kY:-ND0apsuCSjLtgWwk-kZ:b-wrsp4w) ([raw file](https://github.com/sfc-aqua/quisp/blob/a44b2b48595b8e786bc86d3989a4fc914e278137/quisp/runtime/def_instructions.h#L32)):*
> ```objc
> INSTR(STORE, MemoryKey, int)
> 
> // qubit operations
> ```

Where does the gate or quantum operation go? 
I was thinking of what is a good level of abstraction for that though. 
For now, I guess applying quantum gate should be good enough. 


<!-- Sent from Reviewable.io -->

2022-09-28 03:17 UTC, zigen reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/431)* status: 3 of 16 files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @zigen)

___
*[`quisp/runtime/def_instructions.h` line 32 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/431#-ND0apsuCSjLtgWwk-kY:-ND14KRI6MwNNzoLs_pj:b-fr6h8c) ([raw file](https://github.com/sfc-aqua/quisp/blob/a44b2b48595b8e786bc86d3989a4fc914e278137/quisp/runtime/def_instructions.h#L32)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Where does the gate or quantum operation go? 
I was thinking of what is a good level of abstraction for that though. 
For now, I guess applying quantum gate should be good enough. 
</blockquote></details>

this operation calls the actual gate operation through InstructionVisitor -> Runtime -> Runtime::ICallback -> RuleEngine -> IStationaryQubit.
I'll try to implement it today. 


<!-- Sent from Reviewable.io -->

2022-09-29 01:07 UTC, Chibikuri requested changes
> Reviewed 3 of 16 files at r1, 1 of 11 files at r3, 2 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/431)* status: 9 of 20 files reviewed, 4 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[`quisp/runtime/def_opcodes.h` line 35 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/431#-ND5fhmMDdXGB6NQ7iuM:-ND5fhmMDdXGB6NQ7iuN:b-bt9vzp) ([raw file](https://github.com/sfc-aqua/quisp/blob/469c2bf583fb086c11a2cecdff149a2f409d7e77/quisp/runtime/def_opcodes.h#L35)):*
> ```objc
> OP(FREE_QUBIT)
> OP(GATE_X)
> OP(GATE_Z)
> ```

It might be reasonable to prepare Pauli Y gate as well. 
For now, X, Y, Z, H, and CX, CZ should be good enough I guess.
___
*[`quisp/runtime/RuleSet.h` line 30 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/431#-ND5lcK7BYmViXNa_x_A:-ND5lcK7BYmViXNa_x_B:b-6gnfg7) ([raw file](https://github.com/sfc-aqua/quisp/blob/469c2bf583fb086c11a2cecdff149a2f409d7e77/quisp/runtime/RuleSet.h#L30)):*
> ```objc
>   RuleSet(const std::string& name, const std::vector<Rule>& rules) : name(name), rules(rules) {}
>   void finalize();
>   int id;
> ```

Is this the same as the `ruleset_id` in `RuleSet.h`?
___
*[`quisp/runtime/RuleSet.cc` line 6 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/431#-ND5lpen20wr4TxTwGXe:-ND5lpen20wr4TxTwGXf:bzfx0a5) ([raw file](https://github.com/sfc-aqua/quisp/blob/469c2bf583fb086c11a2cecdff149a2f409d7e77/quisp/runtime/RuleSet.cc#L6)):*
> ```cpp
> void Rule::finalize() {}
> 
> void RuleSet::finalize() {
> ```

At this point, does this also care about the order of execution? 
Or is this just for labeling rules?


<!-- Sent from Reviewable.io -->

2022-09-29 12:05 UTC, zigen reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/431)* status: 9 of 20 files reviewed, 4 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[`quisp/runtime/def_opcodes.h` line 35 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/431#-ND5fhmMDdXGB6NQ7iuM:-ND84udr1Cm1EIX_k_FY:b-umukb0) ([raw file](https://github.com/sfc-aqua/quisp/blob/469c2bf583fb086c11a2cecdff149a2f409d7e77/quisp/runtime/def_opcodes.h#L35)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

It might be reasonable to prepare Pauli Y gate as well. 
For now, X, Y, Z, H, and CX, CZ should be good enough I guess.
</blockquote></details>

right. I'll add it while rewriting ActiveActions
___
*[`quisp/runtime/RuleSet.h` line 30 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/431#-ND5lcK7BYmViXNa_x_A:-ND86Vgy4cQCmsSXqO93:b-krtpff) ([raw file](https://github.com/sfc-aqua/quisp/blob/469c2bf583fb086c11a2cecdff149a2f409d7e77/quisp/runtime/RuleSet.h#L30)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Is this the same as the `ruleset_id` in `RuleSet.h`?
</blockquote></details>

yes. `RuleSet.ruleset_id` is redundant. should be `RuleSet.id` right?
___
*[`quisp/runtime/RuleSet.cc` line 6 at r4](https://reviewable.io/reviews/sfc-aqua/quisp/431#-ND5lpen20wr4TxTwGXe:-ND86qZH0rUh4PkX3K9g:b-c3u7r) ([raw file](https://github.com/sfc-aqua/quisp/blob/469c2bf583fb086c11a2cecdff149a2f409d7e77/quisp/runtime/RuleSet.cc#L6)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

At this point, does this also care about the order of execution? 
Or is this just for labeling rules?
</blockquote></details>

this cares about the order of execution. 
 I'm still considering how we can describe `next_rule_id`. 


<!-- Sent from Reviewable.io -->

2022-10-04 02:26 UTC, Chibikuri reviewed
> Reviewed 1 of 16 files at r1, 1 of 7 files at r2, 4 of 11 files at r3, 3 of 6 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/431)* status: all files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @zigen)



<!-- Sent from Reviewable.io -->

2022-10-27 07:34 UTC, Chibikuri requested changes
> Reviewed 1 of 19 files at r7, 3 of 26 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/431)* status: 11 of 36 files reviewed, 5 unresolved discussions (waiting on @zigen)

___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.h` line 52 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFNK3nB0nEvJxKPau1e:-NFNK3nB0nEvJxKPau1f:br5vywo) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuleEngine.h#L52)):*
> ```objc
>   int shared_tag;
>   int new_partner_addr;
>   int swapper_addr;
> ```

We can remove this 'swapper_addr' later on.
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 235 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFNLMjW6qf23zPi8H6G:-NFNLMjW6qf23zPi8H6H:b-vfpa28) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L235)):*
> ```cpp
>         .swapper_addr = pkt->getSrcAddr(),
>         .operation_type = pkt->getOperation_type(),
>         .qubit_index = pkt->getMeasured_qubit_index()  // qubit index for this node, the name is misleading
> ```

I guess this is making a bug. This value is gotten by address, but it says index. Is this supposed to be an index of qubits or an address of qubits? (I guess this is not related to the current PR though.)


<!-- Sent from Reviewable.io -->

2022-10-28 05:33 UTC, Chibikuri requested changes
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/431)* status: 11 of 36 files reviewed, 11 unresolved discussions (waiting on @zigen)

___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 183 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFRwnqa8FlWhRR9Ga0j:-NFRwnqb8UpW8UixCmPb:b-yankyw) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L183)):*
> ```cpp
>         .action_index = pkt->getAction_index(),
>         .shared_tag = pkt->getShared_tag(),
>         .type = rules::PurType::SINGLE_X  // TODO: read from pkt
> ```

Is this replaced in this PR or later?
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 187 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFRx3nS1x5HWhm_OtA0:-NFRx3nS1x5HWhm_OtA1:b-rm23yz) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L187)):*
> ```cpp
>     handlePurificationResult(key, PurificationResultData{.is_x_plus = pkt->getOutput_is_plus()}, from_self);
>   } else if (auto *pkt = dynamic_cast<DoublePurificationResult *>(msg)) {
>     error("DoublePurification is not implemented yet");
> ```

Is this "not implemented yet" message for telling result handling cannot be done here? Or this should not happen in the simulation?
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 441 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFRxsZVAZTQEtZx76wv:-NFRxsZVAZTQEtZx76ww:btgbqy5) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L441)):*
> ```cpp
>     return new RandomMeasureAction(ruleset_id, rule_id, act->owner_address, qnic_interface.partner_addr, qnic_interface.qnic_type, qnic_interface.qnic_id, 0, act->num_measurement);
>   }
>   return nullptr;
> ```

Can we set here "error()"?
I guess the situation we reach this point is only when the RE gets an unknown packet type.
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 450 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFRyZc29rtRJbaqECSd:-NFRyZc29rtRJbaqECSe:b-s5jyq9) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L450)):*
> ```cpp
>     return;
>   }
>   // rule_id might be different from other node's rule, so use rule id comes from our runtime
> ```

Are these values different?
If we can identify the counterpart like this, we may be able to remove shared_tag later.
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 487 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFS-_UX9qSxcvtcXyah:-NFS-_UX9qSxcvtcXyai:b-34owdb) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L487)):*
> ```cpp
>   }
> 
>   if (qubit == nullptr) error("cannot found the qubit for purification result");
> ```

typo
cannot found -> cannot find
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 1175 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFS3pWJA8ff8vMlI7xR:-NFS3pWJA8ff8vMlI7xS:bgvhntj) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L1175)):*
> ```cpp
>           qubit_record->setAllocated(true);
>           // qubit_record->markRuleApplied((*rule)->rule_id);
>           runtime.assignQubitToRuleSet(partner_addr, qubit_record);
> ```

Do we assign qubit to RuleSet first?
So, the runtime is also responsible for distributing resources to Rules. right?


<!-- Sent from Reviewable.io -->

2022-10-28 06:20 UTC, zigen reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/431)* status: 11 of 36 files reviewed, 11 unresolved discussions (waiting on @Chibikuri)

___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.h` line 52 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFNK3nB0nEvJxKPau1e:-NFSE_t-0c6OOU0pJpmV:bl3kbs1) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuleEngine.h#L52)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

We can remove this 'swapper_addr' later on.
</blockquote></details>

oh, right. I'll remove it
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 183 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFRwnqa8FlWhRR9Ga0j:-NFSELPo2y_CSIfs_oMd:b-efp4z5) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L183)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Is this replaced in this PR or later?
</blockquote></details>

now I'm replacing it in this PR
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 187 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFRx3nS1x5HWhm_OtA0:-NFSE69BASyzrgoiTWJA:bjul7h0) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L187)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Is this "not implemented yet" message for telling result handling cannot be done here? Or this should not happen in the simulation?
</blockquote></details>

this will be removed later. it's just for debugging.
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 235 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFNLMjW6qf23zPi8H6G:-NFSEFNuALZPhpVrdXMb:b-s681ul) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L235)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

I guess this is making a bug. This value is gotten by address, but it says index. Is this supposed to be an index of qubits or an address of qubits? (I guess this is not related to the current PR though.)
</blockquote></details>

that's a good point. let me check.
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 441 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFRxsZVAZTQEtZx76wv:-NFSDnNOAN9EYPdmF1OK:b-fhp8cj) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L441)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Can we set here "error()"?
I guess the situation we reach this point is only when the RE gets an unknown packet type.
</blockquote></details>

I'll remove this method, and RuleSet conversion is placed in `RuleSetConverter` class
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 1175 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFS3pWJA8ff8vMlI7xR:-NFSCugv8gsZ3R50P4zy:bb45m7o) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L1175)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Do we assign qubit to RuleSet first?
So, the runtime is also responsible for distributing resources to Rules. right?
</blockquote></details>

right, RuleEngine is responsible for assigning qubit to RuleSet/Runtime, and Runtime is responsible for distributing the given resource to a rule.

for now, a Runtime is corresponding to one RuleSet, so I should rename it to `assignQubit`.


<!-- Sent from Reviewable.io -->

2022-10-28 07:24 UTC, Chibikuri requested changes
> Reviewed 1 of 19 files at r7, 1 of 26 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/431)* status: 12 of 36 files reviewed, 14 unresolved discussions (waiting on @zigen)

___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 41 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFSREqGAMvkGano9nlJ:-NFSREqGAMvkGano9nlK:b-iq38nf) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L41)):*
> ```objc
>     auto *qubit = provider.getStationaryQubit(qubit_rec);
>     assert(qubit != nullptr);
>     qubit->xGate();
> ```

Is this supposed to be Clifford backend version?
What about applying X_gate()?



_Code quote:_
```objc
    qubit->xGate();
```
___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 55 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFSRUblDy5VuPo3BGKB:-NFSRUblDy5VuPo3BGKC:b-aw2yu5) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L55)):*
> ```objc
>     assert(control_qubit != nullptr);
>     assert(target_qubit != nullptr);
>     target_qubit->CNOT_gate(control_qubit);
> ```

I guess this CNOT is error basis, so the X and Z gates above shouldn't also be error basis?
___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 74 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFSSWfZ3K_HHz5jQvas:-NFSSWfZ3K_HHz5jQvat:b-4jm781) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L74)):*
> ```objc
>   }
> 
>   void sendLinkTomographyResult(const unsigned long ruleset_id, const runtime::Rule &rule, const int action_index, const runtime::QNodeAddr partner_addr, int count,
> ```

Can we align 'runtime::QNodeAddr' or just 'QNodeAddr' below?


<!-- Sent from Reviewable.io -->

2022-10-28 08:08 UTC, Chibikuri requested changes
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/431)* status: 12 of 36 files reviewed, 15 unresolved discussions (waiting on @zigen)

___
*[`quisp/modules/QRSA/RuleEngine/PurificationResultTable/PurificationResultTable.h` line 14 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFSXKOj2GTBmZ3X7p2f:-NFSXKOj2GTBmZ3X7p2g:bn68n0q) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/PurificationResultTable/PurificationResultTable.h#L14)):*
> ```objc
>   int action_index = -1;
>   int shared_tag = -1;
>   rules::PurType type;
> ```

Can the purification type be a key?
If we assume the base actions, we could think of a new purification type that doesn't have a name on it.


<!-- Sent from Reviewable.io -->

2022-10-28 16:03 UTC, zigen reviewed
> Reviewed 1 of 13 files at r10.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/431)* status: 12 of 37 files reviewed, 14 unresolved discussions (waiting on @Chibikuri)

___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.h` line 52 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFNK3nB0nEvJxKPau1e:-NFTlJo1ASysmNraFYCv:brpmqb3) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuleEngine.h#L52)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

oh, right. I'll remove it
</blockquote></details>

removed
___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 41 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFSREqGAMvkGano9nlJ:-NFTjYxM7FGlOFFBkpk8:b-nhhr6s) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L41)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Is this supposed to be Clifford backend version?
What about applying X_gate()?
</blockquote></details>

ah, it should be `X_gate()`.
___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 55 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFSRUblDy5VuPo3BGKB:-NFTjwlS-BDI2iM1jmJ6:brnw12r) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L55)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

I guess this CNOT is error basis, so the X and Z gates above shouldn't also be error basis?
</blockquote></details>

it should be the error basis. clifford backend is not fully implemented yet


<!-- Sent from Reviewable.io -->

2022-10-30 02:03 UTC, Chibikuri requested changes
> Reviewed 5 of 26 files at r8, 1 of 11 files at r9, 4 of 13 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/431)* status: 21 of 37 files reviewed, 12 unresolved discussions (waiting on @zigen)

___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 55 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFSRUblDy5VuPo3BGKB:-NFaZJkCBM--NJtS9Ww5:b-befro2) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L55)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

it should be the error basis. clifford backend is not fully implemented yet
</blockquote></details>

Yeah, that's also my expectation.
___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 137 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFaZq055suMHoYaGfzT:-NFaZq055suMHoYaGfzU:bvzsh1) ([raw file](https://github.com/sfc-aqua/quisp/blob/faf94dbf4b8654d0d302d4ff2ce6f2e8b30facd8/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L137)):*
> ```objc
>   void sendTriplePurificationResult(const unsigned long ruleset_id, const runtime::Rule &rule, const int action_index, const QNodeAddr partner_addr, bool result_z, bool result_x,
>                                     bool result_ds, int pur_type) override {
>     auto *pkt = new DS_DoublePurificationSecondResult{"DS_DoublePurificationResult"};
> ```

We might want to rename this packet's name from 'DS_DoublePurificationResult' to 'DS_DoublePurificationSecondResult'.
___
*[`quisp/modules/QRSA/RuleEngine/RuleSetConverter/RuleSetConverter.cc` line 53 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFa_yyA6YdQgONdsxDU:-NFa_yyA6YdQgONdsxDV:b5lzede) ([raw file](https://github.com/sfc-aqua/quisp/blob/faf94dbf4b8654d0d302d4ff2ce6f2e8b30facd8/quisp/modules/QRSA/RuleEngine/RuleSetConverter/RuleSetConverter.cc#L53)):*
> ```cpp
> 
>       /*
>         SET temp_qubit_id -1
> ```

What was the 'temp_qubit_id' here? 
I might be missing something, but is this supposed to be some register value?
___
*[`quisp/modules/QRSA/RuleEngine/RuleSetConverter/RuleSetConverter.cc` line 166 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFaawSHCrfV2VRC8a8G:-NFaawSHCrfV2VRC8a8H:b-7zu9gz) ([raw file](https://github.com/sfc-aqua/quisp/blob/faf94dbf4b8654d0d302d4ff2ce6f2e8b30facd8/quisp/modules/QRSA/RuleEngine/RuleSetConverter/RuleSetConverter.cc#L166)):*
> ```cpp
>           // clang-format off
> INSTR_GET_QUBIT_QubitId_QNodeAddr_int_{{q0, left_partner_addr, 0}},
> INSTR_GET_QUBIT_QubitId_QNodeAddr_int_{{q1, right_partner_addr, 0}},
> ```

Isn't this 'INSTR_GET_QUBIT_QubitId_QNodeAddr_int_{{q1, right_partner_addr, 1}}'? 
I thought the id value of the second line should be 1.
___
*[`quisp/modules/QRSA/RuleEngine/RuleSetConverter/RuleSetConverter.cc` line 265 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFabjqZCJU5YwZivPB8:-NFabjqZCJU5YwZivPB9:b-qj0c8x) ([raw file](https://github.com/sfc-aqua/quisp/blob/faf94dbf4b8654d0d302d4ff2ce6f2e8b30facd8/quisp/modules/QRSA/RuleEngine/RuleSetConverter/RuleSetConverter.cc#L265)):*
> ```cpp
> INSTR_GET_QUBIT_QubitId_QNodeAddr_int_{{qubit, partner_addr, 0}},
> INSTR_GET_QUBIT_QubitId_QNodeAddr_int_{{trash_qubit_x, partner_addr, 1}},
> INSTR_GET_QUBIT_QubitId_QNodeAddr_int_{{trash_qubit_z, partner_addr, 1}},
> ```

Isn't this also be 2?


<!-- Sent from Reviewable.io -->

2022-10-30 02:42 UTC, Chibikuri requested changes
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/431)* status: 21 of 37 files reviewed, 11 unresolved discussions (waiting on @zigen)

___
*[`quisp/runtime/InstructionVisitor.cc` line 112 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFaji987wAvdnzB4WJY:-NFaji987wAvdnzB4WJZ:b-16gfbz) ([raw file](https://github.com/sfc-aqua/quisp/blob/faf94dbf4b8654d0d302d4ff2ce6f2e8b30facd8/quisp/runtime/InstructionVisitor.cc#L112)):*
> ```cpp
>   int action_index = rt.getRegVal(reg_id);
>   auto* qubit_rec = rt.getQubitByQubitId(qubit_id);
>   rt.callback->lockQubit(qubit_rec, rt.ruleset.id, rt.rule_id, action_index);
> ```

Is it possible to call the callback function from the runtime directory?
Do we need to dereference once?



_Code quote:_
```cpp
  auto& rt = *runtime;
  int action_index = rt.getRegVal(reg_id);
  auto* qubit_rec = rt.getQubitByQubitId(qubit_id);
  rt.callback->lockQubit(qubit_rec, rt.ruleset.id, rt.rule_id, action_index);
```


<!-- Sent from Reviewable.io -->

2022-11-01 15:08 UTC, zigen reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/431)* status: 18 of 41 files reviewed, 11 unresolved discussions (waiting on @Chibikuri)

___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 450 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFRyZc29rtRJbaqECSd:-NFnhTtn59PicoxwTTRP:bgbve4v) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L450)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Are these values different?
If we can identify the counterpart like this, we may be able to remove shared_tag later.
</blockquote></details>

maybe we can, but I'm not sure. let's try to remove it later.
___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 55 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFSRUblDy5VuPo3BGKB:-NFnhwdI4-MDBPREcFnw:b-7ql1td) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L55)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Yeah, that's also my expectation.
</blockquote></details>

fixed
___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 74 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFSSWfZ3K_HHz5jQvas:-NFni3VO9k4eWZVGHf-l:b-41wt63) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L74)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Can we align 'runtime::QNodeAddr' or just 'QNodeAddr' below?
</blockquote></details>

right, I should do it
___
*[`quisp/modules/QRSA/RuleEngine/RuntimeCallback.h` line 137 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFaZq055suMHoYaGfzT:-NFni9e_4Mn8LSJDXXQC:bp1hvdg) ([raw file](https://github.com/sfc-aqua/quisp/blob/faf94dbf4b8654d0d302d4ff2ce6f2e8b30facd8/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L137)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

We might want to rename this packet's name from 'DS_DoublePurificationResult' to 'DS_DoublePurificationSecondResult'.
</blockquote></details>

oh, I forgot it. thanks.
___
*[`quisp/modules/QRSA/RuleEngine/PurificationResultTable/PurificationResultTable.h` line 14 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFSXKOj2GTBmZ3X7p2f:-NFXaAIK41PQiUcTd1qy:bm6z0mr) ([raw file](https://github.com/sfc-aqua/quisp/blob/1793547cea4b8b16873f9e49de54e878fea36dd7/quisp/modules/QRSA/RuleEngine/PurificationResultTable/PurificationResultTable.h#L14)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Can the purification type be a key?
If we assume the base actions, we could think of a new purification type that doesn't have a name on it.
</blockquote></details>

hmm, that's a good point. but currently, the purification workflow involves RuleEngine and this table, so we need to move this PurificationResult handling part into Runtime.
anyway, we can remove a pur_type from a key.
___
*[`quisp/modules/QRSA/RuleEngine/RuleSetConverter/RuleSetConverter.cc` line 53 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFa_yyA6YdQgONdsxDU:-NFniTfJ49HwoL7YP4kI:b-jiaap2) ([raw file](https://github.com/sfc-aqua/quisp/blob/faf94dbf4b8654d0d302d4ff2ce6f2e8b30facd8/quisp/modules/QRSA/RuleEngine/RuleSetConverter/RuleSetConverter.cc#L53)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

What was the 'temp_qubit_id' here? 
I might be missing something, but is this supposed to be some register value?
</blockquote></details>

that's the remains of my attempt. I'll align the comment to the actual code.
___
*[`quisp/modules/QRSA/RuleEngine/RuleSetConverter/RuleSetConverter.cc` line 166 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFaawSHCrfV2VRC8a8G:-NFnj--h69HMs6h5XE1Y:b-gyijtb) ([raw file](https://github.com/sfc-aqua/quisp/blob/faf94dbf4b8654d0d302d4ff2ce6f2e8b30facd8/quisp/modules/QRSA/RuleEngine/RuleSetConverter/RuleSetConverter.cc#L166)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Isn't this 'INSTR_GET_QUBIT_QubitId_QNodeAddr_int_{{q1, right_partner_addr, 1}}'? 
I thought the id value of the second line should be 1.
</blockquote></details>

thanks. I fixed.
___
*[`quisp/modules/QRSA/RuleEngine/RuleSetConverter/RuleSetConverter.cc` line 265 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFabjqZCJU5YwZivPB8:-NFnisHV5y7RK4sLc5uw:b-uwha7p) ([raw file](https://github.com/sfc-aqua/quisp/blob/faf94dbf4b8654d0d302d4ff2ce6f2e8b30facd8/quisp/modules/QRSA/RuleEngine/RuleSetConverter/RuleSetConverter.cc#L265)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Isn't this also be 2?
</blockquote></details>

yeah, it must be 2. it should be a different value from the above one.
___
*[`quisp/runtime/InstructionVisitor.cc` line 112 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/431#-NFaji987wAvdnzB4WJY:-NFnfYgL7DWHNXJY4aTU:be5i61d) ([raw file](https://github.com/sfc-aqua/quisp/blob/faf94dbf4b8654d0d302d4ff2ce6f2e8b30facd8/quisp/runtime/InstructionVisitor.cc#L112)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Is it possible to call the callback function from the runtime directory?
Do we need to dereference once?
</blockquote></details>

it's possible and intended.
the dereferencing and the assignment is for readability, not for performance.
I think Clang++ optimizes this multiple dereferencing.

maybe I should pass the reference of runtime to InstrVisitor's ctor.


<!-- Sent from Reviewable.io -->

2022-11-11 08:52 UTC, zigen commented
I'm planning to separate the PR into the Runtime implementation part and the application of the Runtime.
for now, I confirmed this implementation works as same as the current master.

2022-11-22 03:10 UTC, closed without merging