Speedup stationary qubit
sfc-aqua/quisp pull request #443
Opened 2022-11-09 15:36 UTC by res6idue

This PR speeds up StationaryQubit by eliminating the usage of par() as normal variables.

2022-11-11 03:53 UTC, zigen requested changes
> Reviewed 2 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @res6idue)

___
*[`quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h` line 123 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NGZn5BID6GDvNFUnQE-:-NGZn5BID6GDvNFUnQE0:b4k6g0y) ([raw file](https://github.com/sfc-aqua/quisp/blob/c71f6670ea3703ace6478fbd280518c1839a1bdc/quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h#L123)):*
> ```objc
> };
> 
> struct GOD_error_model {
> ```

for the new struct/class definition, I want to stick the PascalCase.
and this should be a state, not a model. I think the "error model" contains how we should calculate the error or the related values for it.

so `GodErrorState` seems better.
___
*[`quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h` line 124 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NGZmQ_oESnmHP63YWtR:-NGZmQ_q61PDSYs_Sbq5:b-ydd0ru) ([raw file](https://github.com/sfc-aqua/quisp/blob/c71f6670ea3703ace6478fbd280518c1839a1bdc/quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h#L124)):*
> ```objc
> 
> struct GOD_error_model {
>   bool has_X_error;
> ```

you should put the default initializer. like `bool has_x_error = false` it would be intuitive behavior, right?

https://en.cppreference.com/w/cpp/language/data_members
see "Member Initialization"
___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc` line 98 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NGZoLOg9A-BCoSTz0Fi:-NGZoLOg9A-BCoSTz0Fj:b-4icmpy) ([raw file](https://github.com/sfc-aqua/quisp/blob/c71f6670ea3703ace6478fbd280518c1839a1bdc/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L98)):*
> ```cpp
> 
>   // Get parameters from omnet
>   GOD_entangled_stationaryQubit_address = par("GOD_entangled_stationaryQubit_address");
> ```

no one set the value. so the parameter was used for debugging.
let's use the WATCH macro.
https://doc.omnetpp.org/omnetpp/manual/#sec:sim-lib:basic-watches


<!-- Sent from Reviewable.io -->

2022-11-11 13:44 UTC, zigen reviewed
> Reviewed 5 of 10 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @res6idue)



<!-- Sent from Reviewable.io -->

2022-11-21 05:54 UTC, res6idue reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @zigen)

___
*[`quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h` line 123 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NGZn5BID6GDvNFUnQE-:-NG_rtHqCJpmPkoy1eYU:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/c71f6670ea3703ace6478fbd280518c1839a1bdc/quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h#L123)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

for the new struct/class definition, I want to stick the PascalCase.
and this should be a state, not a model. I think the "error model" contains how we should calculate the error or the related values for it.

so `GodErrorState` seems better.
</blockquote></details>

Done.
___
*[`quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h` line 124 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NGZmQ_oESnmHP63YWtR:-NH8Yho93VEwwE1Jrm5a:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/c71f6670ea3703ace6478fbd280518c1839a1bdc/quisp/modules/QNIC/StationaryQubit/IStationaryQubit.h#L124)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

you should put the default initializer. like `bool has_x_error = false` it would be intuitive behavior, right?

https://en.cppreference.com/w/cpp/language/data_members
see "Member Initialization"
</blockquote></details>

Done.
___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc` line 98 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NGZoLOg9A-BCoSTz0Fi:-NH8Z4LbAB2hd_UQ8AXp:bevetcc) ([raw file](https://github.com/sfc-aqua/quisp/blob/c71f6670ea3703ace6478fbd280518c1839a1bdc/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L98)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

no one set the value. so the parameter was used for debugging.
let's use the WATCH macro.
https://doc.omnetpp.org/omnetpp/manual/#sec:sim-lib:basic-watches
</blockquote></details>

Should we have to modify this inside this PR?


<!-- Sent from Reviewable.io -->

2022-11-21 07:26 UTC, zigen commented
@res6idue hey, could you rebase this?

2022-11-22 10:59 UTC, res6idue reviewed
I think in PR#451, we normalized NED parameters. Should we stick to the current convention for GOD_err, like 
`GOD_err.has_CM_error`, or change them into `god_err.has_completely_mixed_error`?

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443#-:-NHTycXS0TWyNNTzwcWp:b-tc1kv5)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @zigen)



<!-- Sent from Reviewable.io -->

2022-11-22 11:05 UTC, zigen requested changes
We don't need to stick with the current weird conventions. The strange conventions prevent automatic checks for the naming with clang-tidy. And also, this naming confuses us whether it is a class name or a member name.

> Reviewed 1 of 10 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 1 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443#-:-NHTzs3G8bDDtQaQpQZP:bspfab5)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @res6idue)

___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc` line 98 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NGZoLOg9A-BCoSTz0Fi:-NHU-Sjw-4WR2mXQCSsa:buawqgl) ([raw file](https://github.com/sfc-aqua/quisp/blob/c71f6670ea3703ace6478fbd280518c1839a1bdc/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L98)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

Should we have to modify this inside this PR?
</blockquote></details>

Up to you. Both are fine.


<!-- Sent from Reviewable.io -->

2022-11-23 05:45 UTC, zigen requested changes
> Reviewed 4 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443)* status: 5 of 12 files reviewed, 4 unresolved discussions (waiting on @res6idue)

___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc` line 62 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NHY-x900vwc1Rw_9WNu:-NHY-x9139eO8kzIM5V6:b-8pqjgi) ([raw file](https://github.com/sfc-aqua/quisp/blob/73f24413f8dc66eca7ef45ec8d9978ee7eb558a3/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L62)):*
> ```cpp
>     0,                          0,                         0,                         0,                          memory_err.excitation_error_rate, memory_err.relaxation_error_rate, 1 - memory_err.excitation_error_rate - memory_err.relaxation_error_rate;
>   // clang-format on
>   god_err.has_x_error = par("god_x_error").boolValue();
> ```

should we initialize it with the `par("god_x_error")` ? 
I think we will never set this state from .ini files
___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc` line 394 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NHY-DSn5FU6nAQ4jklE:-NHY-DSn5FU6nAQ4jklF:bj1ikxt) ([raw file](https://github.com/sfc-aqua/quisp/blob/73f24413f8dc66eca7ef45ec8d9978ee7eb558a3/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L394)):*
> ```cpp
>   EV_DEBUG << "Freeing this qubit!!!" << this << " at qnode: " << node_address << " qnic_type: " << qnic_type << " qnic_index: " << qnic_index << "\n";
>   // GUI part
>   if (hasGUI()) {
> ```

we can remove the GUI part to the `refreshDisplay() const`. 
___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc` line 426 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NHY-SG41qCS3f6faMV_:-NHY-SG41qCS3f6faMVa:b5y2c67) ([raw file](https://github.com/sfc-aqua/quisp/blob/73f24413f8dc66eca7ef45ec8d9978ee7eb558a3/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L426)):*
> ```cpp
>   locked_rule_id = rule_id;
>   action_index = action_id;
>   // GUI part
> ```

I think this comment is useless because we can easily understand it without the comment.


<!-- Sent from Reviewable.io -->

2022-11-24 02:39 UTC, zigen reviewed
> Reviewed 6 of 11 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443)* status: all files reviewed, 2 unresolved discussions (waiting on @res6idue)



<!-- Sent from Reviewable.io -->

2022-12-06 08:36 UTC, zigen requested changes
> Reviewed 7 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443)* status: 12 of 14 files reviewed, 3 unresolved discussions (waiting on @res6idue)

___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit_internal_stabilizer_graph_test.cc` line 86 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NIaYomD9d4Jhn2kOYRz:-NIaYomD9d4Jhn2kOYS-:bgpsj0d) ([raw file](https://github.com/sfc-aqua/quisp/blob/3f949d0aa786188483b53cd0734a8b862d0cd9c3/quisp/modules/QNIC/StationaryQubit/StationaryQubit_internal_stabilizer_graph_test.cc#L86)):*
> ```cpp
>     setParDouble(this, "std", 0.5);
> 
>     setParBool(this, "god_x_error", false);
> ```

you should also remove this. god_x_error is not a parameter 


<!-- Sent from Reviewable.io -->

2022-12-10 12:00 UTC, res6idue reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443)* status: 8 of 14 files reviewed, 3 unresolved discussions (waiting on @zigen)

___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc` line 98 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NGZoLOg9A-BCoSTz0Fi:-NIvtqBF6kdEN7EzAUpK:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/c71f6670ea3703ace6478fbd280518c1839a1bdc/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L98)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

Up to you. Both are fine.
</blockquote></details>

Done.
___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc` line 394 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NHY-DSn5FU6nAQ4jklE:-NIvtqq91bbvH9iPKvi1:b-qic5t) ([raw file](https://github.com/sfc-aqua/quisp/blob/73f24413f8dc66eca7ef45ec8d9978ee7eb558a3/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L394)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

we can remove the GUI part to the `refreshDisplay() const`. 
</blockquote></details>

I felt that the GUI parts were not that similar, so I didn't move them out into a single function. However, I might do this in a future PR.
___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit_internal_stabilizer_graph_test.cc` line 86 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NIaYomD9d4Jhn2kOYRz:-NIvu3tcBCcQksUUoJ4R:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/3f949d0aa786188483b53cd0734a8b862d0cd9c3/quisp/modules/QNIC/StationaryQubit/StationaryQubit_internal_stabilizer_graph_test.cc#L86)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

you should also remove this. god_x_error is not a parameter 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-11 08:25 UTC, Naphann requested changes
Please remove all unused par inside `stationaryqubit.ned` as well. All the `@mutable` par inside it are not required at all except the `std` which should be renamed to `emission_jittering_standard_deviation` or use other distribution as commented to code. 

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443#-:-NJ-HGVm8eeFGEmdojOV:bqnjhcw)* status: 8 of 14 files reviewed, 7 unresolved discussions (waiting on @res6idue and @zigen)

___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned` line 22 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NJ-G1PO3RKHlwd1bymP:-NJ-G1PO3RKHlwd1bymQ:bkoth9t) ([raw file](https://github.com/sfc-aqua/quisp/blob/b6469114b842c9e16f4a36fec1ca8e79bc5ee33b/quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned#L22)):*
> ```
>         int god_entangled_node_address @mutable = default(-1);
>         int god_entangled_qnic_address @mutable = default(-1);
>         int god_entangled_qnic_type @mutable = default(-1);
> ```

I think all `god_entangled_...` does not need to be `par(...)` as well. If already changed then remove these lines.
___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned` line 28 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NJ-GGQB2fQxDhjM94z9:-NJ-GGQB2fQxDhjM94zA:bvm76en) ([raw file](https://github.com/sfc-aqua/quisp/blob/b6469114b842c9e16f4a36fec1ca8e79bc5ee33b/quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned#L28)):*
> ```
>         int x_position_graphics;		// can this be usefully set in a .ned file?
>         bool is_busy @mutable = default(false);
>         double std @mutable = default(0);
> ```

`is_busy` does not need to be set by users. This shouldn't be a par. If already changed then remove these lines.
___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned` line 28 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NJ-GMDE0iY4h34Kvc0J:-NJ-GMDE0iY4h34Kvc0K:b-kl5l9p) ([raw file](https://github.com/sfc-aqua/quisp/blob/b6469114b842c9e16f4a36fec1ca8e79bc5ee33b/quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned#L28)):*
> ```
>         int x_position_graphics;		// can this be usefully set in a .ned file?
>         bool is_busy @mutable = default(false);
>         double std @mutable = default(0);
> ```

This doesn't need to be mutable. And should be rename `emission_jittering_standard_deviation` Or change the way the randomly generated jitter to the exponential distribution or other distribution. If already changed then remove these lines.
___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned` line 43 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NJ-GA2b009cKGwcNLCY:-NJ-GA2b009cKGwcNLCZ:b-ykdx2h) ([raw file](https://github.com/sfc-aqua/quisp/blob/b6469114b842c9e16f4a36fec1ca8e79bc5ee33b/quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned#L43)):*
> ```
>         bool god_excitation_error @mutable = false;//Physical error on qubit
>         bool god_relaxation_error @mutable = false;//Physical error on qubit
>         bool god_completely_mixed_error @mutable = false;//Physical error on qubit
> ```

same here, `god_...` don't need to be par. If already changed then remove these lines.


<!-- Sent from Reviewable.io -->

2022-12-12 04:33 UTC, res6idue reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443)* status: 7 of 14 files reviewed, 7 unresolved discussions (waiting on @Naphann and @zigen)

___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned` line 22 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NJ-G1PO3RKHlwd1bymP:-NJ3au02CzHeMzQspi0-:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/b6469114b842c9e16f4a36fec1ca8e79bc5ee33b/quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned#L22)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

I think all `god_entangled_...` does not need to be `par(...)` as well. If already changed then remove these lines.
</blockquote></details>

Done.
___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned` line 43 at r10](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NJ-GA2b009cKGwcNLCY:-NJ3auu57Lrjb6It8R1-:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/b6469114b842c9e16f4a36fec1ca8e79bc5ee33b/quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned#L43)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

same here, `god_...` don't need to be par. If already changed then remove these lines.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-12 04:53 UTC, Naphann requested changes
> Reviewed 5 of 11 files at r5, 2 of 9 files at r7, 7 of 7 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443)* status: all files reviewed, 6 unresolved discussions (waiting on @res6idue and @zigen)

___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc` line 345 at r11](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NJ3eCkSDGWVy_wqcB25:-NJ3eCkT9Q6gp0aCARij:b72r3mn) ([raw file](https://github.com/sfc-aqua/quisp/blob/8e8978aa4b14c086a9b724fedf2c603049c8338b/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L345)):*
> ```cpp
>   emitted_time = simTime();
>   updated_time = simTime();  // Should be no error at this time.
>   par("photon_emitted_at") = emitted_time.dbl();
> ```

why do we remove these lines?
___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned` line 20 at r11](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NJ3ewbt06bIaRxyQEQJ:-NJ3ewbt06bIaRxyQEQK:b-ymtmlr) ([raw file](https://github.com/sfc-aqua/quisp/blob/e96bf9cf33d8dab43cfe44b9c345c9b4afcb203e/quisp/modules/QNIC/StationaryQubit/StationaryQubit.ned#L20)):*
> This doesn't need to be mutable. And should be rename emission_jittering_standard_deviation Or change the way the randomly generated jitter to the exponential distribution or other distribution. If already changed then remove these lines.

I moved my old comments to here again.


<!-- Sent from Reviewable.io -->

2022-12-12 04:59 UTC, res6idue reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443)* status: all files reviewed, 6 unresolved discussions (waiting on @Naphann and @zigen)

___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc` line 345 at r11](https://reviewable.io/reviews/sfc-aqua/quisp/443#-NJ3eCkSDGWVy_wqcB25:-NJ3g6yt2yFH7t3uNXxn:b2a5czc) ([raw file](https://github.com/sfc-aqua/quisp/blob/8e8978aa4b14c086a9b724fedf2c603049c8338b/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L345)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

why do we remove these lines?
</blockquote></details>

It's because we don't pass simtime in the ned file. And, by using the WATCH macro, we can check the simtime in GUI environment.


<!-- Sent from Reviewable.io -->

2022-12-12 06:16 UTC, zigen approved these changes
> Reviewed 5 of 7 files at r11.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443)* status: all files reviewed, 1 unresolved discussion (waiting on @res6idue)



<!-- Sent from Reviewable.io -->

2022-12-12 13:00 UTC, Naphann requested changes
Please check QNIC.ned and other corresponding files for the remaining `StationaryQubit.std` and rename it accordingly.

> Reviewed 8 of 8 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443#-:-NJ5PEY7Be5_ZLqtd3mi:b-nyswgr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)



<!-- Sent from Reviewable.io -->

2022-12-13 02:08 UTC, Naphann approved these changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)



<!-- Sent from Reviewable.io -->

2022-12-13 02:08 UTC, Naphann approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443#-:-NJ8EOHC7QmggAXPp4n7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)



<!-- Sent from Reviewable.io -->

2022-12-13 03:12 UTC, zigen approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 8 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/443#-:-NJ8SgWGDNHVvYvk-C1i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @res6idue)



<!-- Sent from Reviewable.io -->

2022-12-13 03:28 UTC, merged