Runtime implementation
sfc-aqua/quisp pull request #446
Opened 2022-11-16 04:25 UTC by zigen

2022-11-28 04:48 UTC, res6idue requested changes
> Reviewed 1 of 20 files at r1, 3 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446)* status: 4 of 20 files reviewed, 3 unresolved discussions (waiting on @Naphann, @sierpinskiii, and @zigen)

___
*[`quisp/runtime/def_instructions.h` line 26 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NHwO0HPBXmctyHdnqDr:-NHwO0HPBXmctyHdnqDs:b-owtk3s) ([raw file](https://github.com/sfc-aqua/quisp/blob/b5f00a475ada67ed61da6a085f2cba6a2c4b83f9/quisp/runtime/def_instructions.h#L26)):*
> ```objc
> INSTR(BEZ, Label, RegId)  // branch if the reg value is zero
> INSTR(BNZ, Label, RegId)  // branch if the reg val is not zero
> INSTR(BLT, Label, RegId, int)  // branch if the reg val is less than the int value
> ```

This might be trivial, but I think it is better to have consistency in the comment. So, I think reg value should be renamed to reg val, and regs renamed to reg vals.
___
*[`quisp/runtime/README.md` line 42 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NHwXPZl0WuLX1U--Aot:-NHwXPZl0WuLX1U--Aou:b8ti2t3) ([raw file](https://github.com/sfc-aqua/quisp/blob/b5f00a475ada67ed61da6a085f2cba6a2c4b83f9/quisp/runtime/README.md#L42)):*
> ```Markdown
> 
>   // measure the qubit q0 and store the result to the "outcome" key
>   MEASURE_RONDOM "outcome" q0
> ```

Is this a spelling mistake?
___
*[`quisp/runtime/README.md` line 94 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NHwYbpjCFneKmISz8Y7:-NHwYbpjCFneKmISz8Y8:b4rk30z) ([raw file](https://github.com/sfc-aqua/quisp/blob/b5f00a475ada67ed61da6a085f2cba6a2c4b83f9/quisp/runtime/README.md#L94)):*
> ```Markdown
> 
> ## RuleSet Execution with Runtime
> @htmlonly
> ```

How can I read this?


<!-- Sent from Reviewable.io -->

2022-11-28 05:07 UTC, res6idue reviewed
When I was running the unit test, 
```
[ RUN      ] RuntimeInstructionsTest.ERROR
Uncaught Error >>>>>> 

---------runtime-state---------
pc: 2, rule_id: 0, qubit_found: false
Reg0: 1, Reg1: 0, Reg2: 0, Reg3: 0, Reg4: 0
----------memory------------

----------qubits---------

--------named-qubits---------
----------------------------------------


 
    0: SET REG0, 1, 
    1: RET ERROR, 
  >>2: SET REG1, 1, 
    3: SET REG2, 1, 
```
This came out. Is this a desired action?

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446#-:-NHwcNuBDxz27fj_RcUu:b-xdfzqv)* status: 4 of 20 files reviewed, 3 unresolved discussions (waiting on @Naphann, @sierpinskiii, and @zigen)



<!-- Sent from Reviewable.io -->

2022-11-28 05:25 UTC, zigen reviewed
This is intentional. but I know we don't want to spill it out on the standard output. let me think.

> Reviewed 1 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446#-:-NHwgHkgBbwqw5EAxQVH:bhrn68e)* status: 4 of 20 files reviewed, 3 unresolved discussions (waiting on @Naphann, @res6idue, and @sierpinskiii)

___
*[`quisp/runtime/def_instructions.h` line 26 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NHwO0HPBXmctyHdnqDr:-NHwgcVd9UJs44z5gW6-:b2k0a5v) ([raw file](https://github.com/sfc-aqua/quisp/blob/b5f00a475ada67ed61da6a085f2cba6a2c4b83f9/quisp/runtime/def_instructions.h#L26)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

This might be trivial, but I think it is better to have consistency in the comment. So, I think reg value should be renamed to reg val, and regs renamed to reg vals.
</blockquote></details>

That's right. let me fix it
___
*[`quisp/runtime/README.md` line 42 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NHwXPZl0WuLX1U--Aot:-NHwgC4-DRb7skweDGQw:b-8o83o4) ([raw file](https://github.com/sfc-aqua/quisp/blob/b5f00a475ada67ed61da6a085f2cba6a2c4b83f9/quisp/runtime/README.md#L42)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

Is this a spelling mistake?
</blockquote></details>

right. I'll fix it. thanks for pointing it
___
*[`quisp/runtime/README.md` line 94 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NHwYbpjCFneKmISz8Y7:-NHwfcm0DQr8znDme_Mp:b-ovj6dp) ([raw file](https://github.com/sfc-aqua/quisp/blob/b5f00a475ada67ed61da6a085f2cba6a2c4b83f9/quisp/runtime/README.md#L94)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

How can I read this?
</blockquote></details>

Run `$ doxygen` and then you can get the documentation for this in `/doc/html/index.html`


<!-- Sent from Reviewable.io -->

2022-11-28 07:50 UTC, res6idue requested changes
> Reviewed 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446)* status: 4 of 20 files reviewed, 4 unresolved discussions (waiting on @Naphann, @sierpinskiii, and @zigen)

___
*[`quisp/runtime/def_instructions.h` line 63 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NHxC7HtB1dMLeQPGTM-:-NHxC7HtB1dMLeQPGTM0:b-31oq2d) ([raw file](https://github.com/sfc-aqua/quisp/blob/b5f00a475ada67ed61da6a085f2cba6a2c4b83f9/quisp/runtime/def_instructions.h#L63)):*
> ```objc
> 
> // hacks. will be deleted
> INSTR(HACK_SWAPPING_PARTNERS, QubitId, QubitId)
> ```

I tried to look for the implementation for this part, but I couldn't find hack-related things in `Runtime.cc`, although I found the declaration for those in `Runtime.h`. Have you just forgot to delete these?
___
*[`quisp/runtime/README.md` line 118 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NHx8ckE0krRZrSex5nj:-NHx8ckE0krRZrSex5nk:b-zhnx5c) ([raw file](https://github.com/sfc-aqua/quisp/blob/b5f00a475ada67ed61da6a085f2cba6a2c4b83f9/quisp/runtime/README.md#L118)):*
> ```Markdown
>             RT->>-RE: finish RuleSet execution
>         else RuleSet terminated
>             RT->>RE: finsih RuleSet execution
> ```

I think this is also a typo.


<!-- Sent from Reviewable.io -->

2022-11-28 14:03 UTC, zigen reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446)* status: 0 of 20 files reviewed, 4 unresolved discussions (waiting on @Naphann, @res6idue, and @sierpinskiii)

___
*[`quisp/runtime/def_instructions.h` line 26 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NHwO0HPBXmctyHdnqDr:-NHyY-NT-6rXJCao72Qw:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/b5f00a475ada67ed61da6a085f2cba6a2c4b83f9/quisp/runtime/def_instructions.h#L26)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

That's right. let me fix it
</blockquote></details>

Done.
___
*[`quisp/runtime/def_instructions.h` line 63 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NHxC7HtB1dMLeQPGTM-:-NHyWtFc9MnszQgc5JG4:bpf5ugx) ([raw file](https://github.com/sfc-aqua/quisp/blob/b5f00a475ada67ed61da6a085f2cba6a2c4b83f9/quisp/runtime/def_instructions.h#L63)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

I tried to look for the implementation for this part, but I couldn't find hack-related things in `Runtime.cc`, although I found the declaration for those in `Runtime.h`. Have you just forgot to delete these?
</blockquote></details>

Actually, these hacks are in the next PR. Sorry for the inconvenience. 
https://github.com/sfc-aqua/quisp/blob/55759456f72ddfbc2ed4aa67c6e04113edeed0bd/quisp/modules/QRSA/RuleEngine/RuntimeCallback.h#L224-L256
___
*[`quisp/runtime/README.md` line 42 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NHwXPZl0WuLX1U--Aot:-NHyY37l2WyLh4ej-J3g:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/b5f00a475ada67ed61da6a085f2cba6a2c4b83f9/quisp/runtime/README.md#L42)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

right. I'll fix it. thanks for pointing it
</blockquote></details>

Done.
___
*[`quisp/runtime/README.md` line 118 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NHx8ckE0krRZrSex5nj:-NHyXvSx-x9aIWPca8M2:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/b5f00a475ada67ed61da6a085f2cba6a2c4b83f9/quisp/runtime/README.md#L118)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

I think this is also a typo.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-07 11:56 UTC, Naphann requested changes
> Reviewed 6 of 20 files at r1, 4 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446)* status: 9 of 20 files reviewed, 6 unresolved discussions (waiting on @res6idue, @sierpinskiii, and @zigen)

___
*[`quisp/runtime/def_instructions.h` line 42 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIgR4cI2aOR4f_GCqxE:-NIgR4cI2aOR4f_GCqxF:balgn83) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/def_instructions.h#L42)):*
> ```objc
> 
> // qubit operations
> INSTR(GET_QUBIT, QubitId, QNodeAddr, int)  // may throw "no qubit error"
> ```

What does `QubitId` mean in this context? Do we need to know some kind of ID for the qubit before using it? And what does ID refers to?
___
*[`quisp/runtime/def_opcodes.h` line 49 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIgPuiS31T0XhtKGc7R:-NIgPuiS31T0XhtKGc7S:bf2qcrn) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/def_opcodes.h#L49)):*
> ```objc
> OP(SEND_LINK_TOMOGRAPHY_RESULT)
> OP(SEND_PURIFICATION_RESULT)
> OP(SEND_SWAPPING_RESULT)
> ```

Do we need specific messages for sending classical message operations? Does that mean that we need new instructions when we want to send new kinds of messages?


<!-- Sent from Reviewable.io -->

2022-12-07 11:59 UTC, Naphann reviewed
I'm still a confused on the difference between program scope and RS scope, can you explain this part?

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446#-:-NIgRuFNCKn6Wu4LgRe3:b78xqhn)* status: 9 of 20 files reviewed, 6 unresolved discussions (waiting on @res6idue, @sierpinskiii, and @zigen)



<!-- Sent from Reviewable.io -->

2022-12-09 15:43 UTC, Naphann requested changes
> Reviewed 2 of 20 files at r1, 5 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446)* status: 16 of 20 files reviewed, 11 unresolved discussions (waiting on @res6idue, @sierpinskiii, and @zigen)

___
*[`quisp/runtime/README.md` line 29 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIrRBpR1R0wPggbrmrT:-NIrRBpR1R0wPggbrmrU:bn1tgup) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/README.md#L29)):*
> ```Markdown
>   LOAD count "count"
> 
>   // find a n-th qubit entangled with partner_addr and set as q0.
> ```

The description can be improved by "get the n-th resource qubit pointer that is entangled with partner_addr into q0" and "the qubits are ordered by allocation to the current Rule".
___
*[`quisp/runtime/Runtime.h` line 24 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIrVr8VCZKyCg5JI6G7:-NIrVr8VCZKyCg5JI6G8:b2eyc9k) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime.h#L24)):*
> ```objc
> };
> 
> // (partner's qnode addr, assigned RuleId) => [half bell pair qubit record]
> ```

Something something about the half Bell pair terminology rdv mentioned a few weeks ago. Maybe `local half of the bell pair` is better?
___
*[`quisp/runtime/Runtime.h` line 60 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIrWKRe8AEuO8mnwRkt:-NIrWKRe8AEuO8mnwRku:b844i7x) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime.h#L60)):*
> ```objc
>     virtual MeasurementOutcome measureQubitZ(IQubitRecord*) = 0;
>     virtual void gateX(IQubitRecord*) = 0;
>     virtual void gateZ(IQubitRecord*) = 0;
> ```

Why is there no measurement in Y basis? Is this intended?
___
*[`quisp/runtime/Runtime.h` line 317 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIrWjdwBRBiaDu1W1xg:-NIrWjdwBRBiaDu1W1xh:bc67jto) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime.h#L317)):*
> ```objc
>    * Before each Program execution, Runtime initializes these registers with 0.
>    */
>   Register registers[5];
> ```

Why 5? Is this just arbitrary?
___
*[`quisp/runtime/Runtime.cc` line 23 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIrXOWY3aF0_Qk2Lm35:-NIrXOWY3aF0_Qk2Lm36:bzfbese) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime.cc#L23)):*
> ```cpp
> Runtime::~Runtime() {}
> 
> void Runtime::exec() {
> ```

Correct me if I'm wrong. Is this the function to call when a new event occurs at RuleEngine and we want to try and run the RS again in case more conditions are fulfilled? 


<!-- Sent from Reviewable.io -->

2022-12-13 09:46 UTC, zigen reviewed
RS scope means the variable can be stored while the RuleSet is alive. program scope variables are initialized before each Program execution.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446#-:-NJ3zGCAA-vJ-O_cJc75:b-imyil5)* status: 16 of 20 files reviewed, 11 unresolved discussions (waiting on @Naphann, @res6idue, and @sierpinskiii)

___
*[`quisp/runtime/def_instructions.h` line 42 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIgR4cI2aOR4f_GCqxE:-NJ9rfXG18Vng-UX619K:b-1bfe6r) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/def_instructions.h#L42)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

What does `QubitId` mean in this context? Do we need to know some kind of ID for the qubit before using it? And what does ID refers to?
</blockquote></details>

In this context, it's like a qubit-type variable identifier in the IR. this operation name the qubit as the QubitId
___
*[`quisp/runtime/def_opcodes.h` line 49 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIgPuiS31T0XhtKGc7R:-NJ3zjU572OqtnBBenxD:b-mwfn3f) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/def_opcodes.h#L49)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Do we need specific messages for sending classical message operations? Does that mean that we need new instructions when we want to send new kinds of messages?
</blockquote></details>

yes, we need it for now. In the future, we can allow the creation of an arbitrary classical message and send it.
But to do this, we need to change the RuleEngine. 
___
*[`quisp/runtime/Runtime.h` line 24 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIrVr8VCZKyCg5JI6G7:-NJ9s5WpExedZnS0T5KN:b7d1zp5) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime.h#L24)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Something something about the half Bell pair terminology rdv mentioned a few weeks ago. Maybe `local half of the bell pair` is better?
</blockquote></details>

That sounds clearer. Let me fix it.
___
*[`quisp/runtime/Runtime.h` line 60 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIrWKRe8AEuO8mnwRkt:-NJ9oJfN1adgH-DY5mOX:bymn828) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime.h#L60)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Why is there no measurement in Y basis? Is this intended?
</blockquote></details>

I didn't implement methods that are not used for rewriting the current RuleSet. It's intentional.
___
*[`quisp/runtime/Runtime.h` line 317 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIrWjdwBRBiaDu1W1xg:-NJ9pHcr0ixDl5q97dcr:b-bvhu0t) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime.h#L317)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Why 5? Is this just arbitrary?
</blockquote></details>

This is the minimum number for rewriting the original RuleSet. 
___
*[`quisp/runtime/Runtime.cc` line 23 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIrXOWY3aF0_Qk2Lm35:-NJ9qhB10Q0lTMwVjIKA:b-dvpagh) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime.cc#L23)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Correct me if I'm wrong. Is this the function to call when a new event occurs at RuleEngine and we want to try and run the RS again in case more conditions are fulfilled? 
</blockquote></details>

Yes. that's right. you can see how to use it in the next PR.


<!-- Sent from Reviewable.io -->

2022-12-13 09:58 UTC, Naphann reviewed
> Reviewed 2 of 20 files at r1, 2 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446)* status: all files reviewed, 6 unresolved discussions (waiting on @res6idue, @sierpinskiii, and @zigen)



<!-- Sent from Reviewable.io -->

2022-12-13 18:55 UTC, sierpinskiii reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 10 of 20 files at r1, 1 of 10 files at r2, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446#-:-NJ46lvL-RyLtfNUsyzs:bnfp4nl)* status: all files reviewed, 16 unresolved discussions (waiting on @Naphann, @res6idue, and @zigen)

___
*[`quisp/runtime/opcode.h` line 54 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBh0tiBQheJ06JBttA:-NJBh0tiBQheJ06JBttB:b3swqeg) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/opcode.h#L54)):*
> ```objc
>   std::string label;
> 
>   /// @brief returns string representation for debugging
> ```

If we define the class, say, the 'thin wrapper' around the std i/o, it would reduce the hassle modifying every output parts of the project.
___
*[`quisp/runtime/opcode.h` line 71 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBkp8A0EE5bRbZVdxu:-NJBkp8BEoGwJylkagap:br53zcw) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/opcode.h#L71)):*
> ```objc
>       const auto& x = std::get<N>(t);
>       s << x << ", ";
>       toStringArgs<N + 1>(t, s);
> ```

It would be awesome if someone can write a comment here, confirming this recursion will not cause the stack overflow in the future, so that we can code without worries.
___
*[`quisp/runtime/RuleSet.h` line 20 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBiwnrDzlHhp6TtnG4:-NJBiwnrDzlHhp6TtnG5:bt1d8ia) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/RuleSet.h#L20)):*
> ```objc
>   Program(const std::string& name, const std::vector<InstructionTypes>& opcodes, bool debugging = false);
> 
>   std::vector<InstructionTypes> opcodes;
> ```

`deque` is usually faster than `vector`, as long as I know. If there's no pointer arithmetic occurring with `InstructionTypes`, how about replacing this with `deque`?
___
*[`quisp/runtime/RuleSet.cc` line 28 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBp8oW15wA2aSr6cHV:-NJBp8oW15wA2aSr6cHW:b8yx4my) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/RuleSet.cc#L28)):*
> ```cpp
>   }
> 
>   // collect partner addresses and initial rules
> ```

I personally find out myself struggling to understand what's happening in this part. What would be the basic definition of the 'partner'?
___
*[`quisp/runtime/Runtime.h` line 265 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBnxDgBr8dDxleyU9h:-NJBnxDgBr8dDxleyU9i:b-2yy6sa) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime.h#L265)):*
> ```objc
>   /// @brief free qubit and release it from the Rule and the RuleSet
>   void freeQubit(QubitId);
> ```

Is there any future plan to support more gate operations in the future? If not, I want to learn why these gates are already sufficient for our simulation.
___
*[`quisp/runtime/Runtime.h` line 317 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIrWjdwBRBiaDu1W1xg:-NJBcmNNAQLb2S69Nf3H:b-shhkqq) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime.h#L317)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

This is the minimum number for rewriting the original RuleSet. 
</blockquote></details>

So far by my understanding, 5 being minimum is related to the nature of the underlying theories regarding RuleSet, am I correct?
If then could you please help me understanding this more deeply by pointing out the paper or the article regarding this part?
___
*[`quisp/runtime/Runtime.cc` line 263 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIwx6m21nExtFFwmQ5g:-NIwx6m21nExtFFwmQ5h:byqygx1) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime.cc#L263)):*
> ```cpp
> bool Runtime::isQubitLocked(IQubitRecord* const qubit) { return callback->isQubitLocked(qubit); }
> void Runtime::debugRuntimeState() {
>   std::cout << "\n---------runtime-state---------"
> ```

Perhaps we can make here a bit simpler?
___
*[`quisp/runtime/Runtime_instructions_test.cc` line 34 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBm_qE86w5GDzPk6Oq:-NJBm_qE86w5GDzPk6Or:b-6e74yx) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime_instructions_test.cc#L34)):*
> ```cpp
>   }
> 
>   void TearDown() { delete runtime; }
> ```

Should we mention in the comment that this comes from gtest?
___
*[`quisp/runtime/types.cc` line 1 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJB_ZYiA39bx6NI6gZr:-NJB_ZYiA39bx6NI6gZs:b-r9ftu8) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/types.cc#L1)):*
> ```cpp
> #include "types.h"
> ```

I think every files should have a brief explanation (textbook style) of its usage and structure on the top. Or writing a wiki page for that might be a good option as well.
This will help not just beginners, but experienced programmers to maintain the immutable role of each files.
In this case, "<types.cc> contains the definitions of all the user-defined types widely used alongside the simulator..." might be a good starting point.
___
*[`quisp/runtime/Value.h` line 14 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBbJciC9jok4gadj0n:-NJBbJciC9jok4gadj0o:b-eydr6l) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Value.h#L14)):*
> ```objc
> };
> 
> /// @brief enum for memory value types
> ```

This is something of a Type itself as well. If I didn't misunderstood anything, moving this into `types.h` might be an option too.
___
*[`quisp/runtime/Value.h` line 20 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBeJjA3kRJzbLac0TN:-NJBeJjA3kRJzbLac0TO:bic0st2) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Value.h#L20)):*
> ```objc
> };
> 
> /// @brief memory value
> ```

What would be the biggest reason, or say, the biggest key difference for the MemoryValue to be defined as a class, not a struct?
My guess is, because struct shares the function inside, which is defined only once, unlike the class definition. 
If then, this would mean something such as MemoryValue handling the member function's mutability issue in somewhere else.


<!-- Sent from Reviewable.io -->

2022-12-14 03:31 UTC, Naphann reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446)* status: all files reviewed, 16 unresolved discussions (waiting on @res6idue, @sierpinskiii, and @zigen)

___
*[`quisp/runtime/RuleSet.h` line 20 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBiwnrDzlHhp6TtnG4:-NJDcQAZ9Sz-_lQssh2C:b-izc3vg) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/RuleSet.h#L20)):*
<details><summary><i>Previously, sierpinskiii (collodi) wrote…</i></summary><blockquote>

`deque` is usually faster than `vector`, as long as I know. If there's no pointer arithmetic occurring with `InstructionTypes`, how about replacing this with `deque`?
</blockquote></details>

No in general. And `opcodes` needs to have access by index to support jump operations. So we cannot use `deque`.
___
*[`quisp/runtime/RuleSet.cc` line 28 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBp8oW15wA2aSr6cHV:-NJDd4Lt2CxIeowoF8zt:b-hw7kld) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/RuleSet.cc#L28)):*
<details><summary><i>Previously, sierpinskiii (collodi) wrote…</i></summary><blockquote>

I personally find out myself struggling to understand what's happening in this part. What would be the basic definition of the 'partner'?
</blockquote></details>

I agree that we could use a better name. `connection_participating_nodes` is better since we refer to the nodes along the connection path. 
Although I don't think the connection setup behaviour should be written inside the code. You should go read up on "two-pass connection setup" in rdv's paper or quisp paper. 
___
*[`quisp/runtime/Runtime.h` line 265 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBnxDgBr8dDxleyU9h:-NJDdu--9R_eigH0h8AK:b-qim9ew) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime.h#L265)):*
<details><summary><i>Previously, sierpinskiii (collodi) wrote…</i></summary><blockquote>

Is there any future plan to support more gate operations in the future? If not, I want to learn why these gates are already sufficient for our simulation.
</blockquote></details>

reviewable is bad at keeping track of resolved comments. In the current RuleSet we only use these set of operations. But yes we can add more.
___
*[`quisp/runtime/Runtime.h` line 317 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIrWjdwBRBiaDu1W1xg:-NJDe9t39OJIkP6WoZdO:beroi2f) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime.h#L317)):*
<details><summary><i>Previously, sierpinskiii (collodi) wrote…</i></summary><blockquote>

So far by my understanding, 5 being minimum is related to the nature of the underlying theories regarding RuleSet, am I correct?
If then could you please help me understanding this more deeply by pointing out the paper or the article regarding this part?
</blockquote></details>

It will be changed later to variable size. What zigen refers to it being enough is to support the "currently implemented" RuleSet.
___
*[`quisp/runtime/Runtime_instructions_test.cc` line 34 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBm_qE86w5GDzPk6Oq:-NJDcEZ671IUulgAcfPS:b5y4mea) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime_instructions_test.cc#L34)):*
<details><summary><i>Previously, sierpinskiii (collodi) wrote…</i></summary><blockquote>

Should we mention in the comment that this comes from gtest?
</blockquote></details>

I think this is fine as is. Setup and Teardown are common in testing. 
___
*[`quisp/runtime/Value.h` line 14 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBbJciC9jok4gadj0n:-NJDeUGEA9_k7qasd_Ox:b-jqmegz) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Value.h#L14)):*
<details><summary><i>Previously, sierpinskiii (collodi) wrote…</i></summary><blockquote>

This is something of a Type itself as well. If I didn't misunderstood anything, moving this into `types.h` might be an option too.
</blockquote></details>

I kind of disagree, Enum definition should be close to the main usage of it.
___
*[`quisp/runtime/Value.h` line 20 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBeJjA3kRJzbLac0TN:-NJDfSBV2GE79eXmXPNY:b-9j84og) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Value.h#L20)):*
<details><summary><i>Previously, sierpinskiii (collodi) wrote…</i></summary><blockquote>

What would be the biggest reason, or say, the biggest key difference for the MemoryValue to be defined as a class, not a struct?
My guess is, because struct shares the function inside, which is defined only once, unlike the class definition. 
If then, this would mean something such as MemoryValue handling the member function's mutability issue in somewhere else.
</blockquote></details>

The main difference between struct and class is that struct is a value type while class is reference type. 
All members of struct are exposed as public by default. This can be a problem if we want a read-only value so we need to use class instead.


<!-- Sent from Reviewable.io -->

2022-12-14 03:34 UTC, zigen reviewed
> Reviewed 2 of 20 files at r1, 5 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446)* status: all files reviewed, 16 unresolved discussions (waiting on @Naphann, @res6idue, and @sierpinskiii)

___
*[`quisp/runtime/opcode.h` line 54 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBh0tiBQheJ06JBttA:-NJDbHM57I6lWo2qpVHX:bs04fdu) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/opcode.h#L54)):*
<details><summary><i>Previously, sierpinskiii (collodi) wrote…</i></summary><blockquote>

If we define the class, say, the 'thin wrapper' around the std i/o, it would reduce the hassle modifying every output parts of the project.
</blockquote></details>

Yes, we might need it. But for now, I don't have a good implementation idea.
Let's discuss it later.
___
*[`quisp/runtime/opcode.h` line 71 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBkp8A0EE5bRbZVdxu:-NJDbqyv1C5V99r86imF:bx0c737) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/opcode.h#L71)):*
<details><summary><i>Previously, sierpinskiii (collodi) wrote…</i></summary><blockquote>

It would be awesome if someone can write a comment here, confirming this recursion will not cause the stack overflow in the future, so that we can code without worries.
</blockquote></details>

it's a good point. I'll comment on it.
___
*[`quisp/runtime/README.md` line 29 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIrRBpR1R0wPggbrmrT:-NJDejem4-_FzHV0bf2c:b-gpic5m) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/README.md#L29)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

The description can be improved by "get the n-th resource qubit pointer that is entangled with partner_addr into q0" and "the qubits are ordered by allocation to the current Rule".
</blockquote></details>

thanks. I'll fix it.
___
*[`quisp/runtime/RuleSet.h` line 20 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBiwnrDzlHhp6TtnG4:-NJDfA4G5KdfBw00dXQE:bx1cei8) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/RuleSet.h#L20)):*
<details><summary><i>Previously, sierpinskiii (collodi) wrote…</i></summary><blockquote>

`deque` is usually faster than `vector`, as long as I know. If there's no pointer arithmetic occurring with `InstructionTypes`, how about replacing this with `deque`?
</blockquote></details>

It sounds excellent to me. Let me try!
___
*[`quisp/runtime/Runtime_instructions_test.cc` line 34 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBm_qE86w5GDzPk6Oq:-NJDgWZL4iDeiYfFDQ2V:b-ac35xj) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime_instructions_test.cc#L34)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

I think this is fine as is. Setup and Teardown are common in testing. 
</blockquote></details>

It'd be better to have a wiki page for how to write tests or update this README.md https://github.com/sfc-aqua/quisp/blob/master/quisp/test_utils/README.md


<!-- Sent from Reviewable.io -->

2022-12-14 03:44 UTC, zigen reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446)* status: all files reviewed, 16 unresolved discussions (waiting on @Naphann, @res6idue, and @sierpinskiii)

___
*[`quisp/runtime/RuleSet.h` line 20 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBiwnrDzlHhp6TtnG4:-NJDiACF8ZQgf4SjluUG:b-w02kxq) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/RuleSet.h#L20)):*
I understood what whit3z said. Let's keep using std::vector.
thanks you guys.

https://en.cppreference.com/w/cpp/container/deque

> As opposed to std::vector, the elements of a deque are not stored contiguously: typical implementations use a sequence of individually allocated fixed-size arrays, with additional bookkeeping, which means indexed access to deque must perform two pointer dereferences, compared to vector's indexed access which performs only one.


<!-- Sent from Reviewable.io -->

2022-12-14 04:57 UTC, zigen reviewed
> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446)* status: 16 of 20 files reviewed, 16 unresolved discussions (waiting on @Naphann, @res6idue, and @sierpinskiii)

___
*[`quisp/runtime/opcode.h` line 71 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBkp8A0EE5bRbZVdxu:-NJDm7mO98rlEay9Z1R4:b-7ql1td) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/opcode.h#L71)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

it's a good point. I'll comment on it.
</blockquote></details>

fixed
___
*[`quisp/runtime/README.md` line 29 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIrRBpR1R0wPggbrmrT:-NJDmAdyBOnQCJYUnM23:b-7ql1td) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/README.md#L29)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

thanks. I'll fix it.
</blockquote></details>

fixed
___
*[`quisp/runtime/Runtime.h` line 24 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIrVr8VCZKyCg5JI6G7:-NJDmEVqDCa_X8sRhj1l:b-qssebl) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime.h#L24)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

That sounds clearer. Let me fix it.
</blockquote></details>

fixed.
___
*[`quisp/runtime/Runtime.h` line 317 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NIrWjdwBRBiaDu1W1xg:-NJDmU092XRsxufxUDuO:bg35r6o) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime.h#L317)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

It will be changed later to variable size. What zigen refers to it being enough is to support the "currently implemented" RuleSet.
</blockquote></details>

right. "original" means "currently implemented" here. 
___
*[`quisp/runtime/types.cc` line 1 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJB_ZYiA39bx6NI6gZr:-NJDqnjH4Omi38GDCr_j:bnkkco9) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/types.cc#L1)):*
<details><summary><i>Previously, sierpinskiii (collodi) wrote…</i></summary><blockquote>

I think every files should have a brief explanation (textbook style) of its usage and structure on the top. Or writing a wiki page for that might be a good option as well.
This will help not just beginners, but experienced programmers to maintain the immutable role of each files.
In this case, "<types.cc> contains the definitions of all the user-defined types widely used alongside the simulator..." might be a good starting point.
</blockquote></details>

Yeah, for the type.h case, it's ambiguous and unclear what the file contains. 
but basically, it's fine to put it on the header file.
I'll add some comments.
___
*[`quisp/runtime/Value.h` line 14 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBbJciC9jok4gadj0n:-NJDzIqC6q1e6L3AFciD:bybodob) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Value.h#L14)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

I kind of disagree, Enum definition should be close to the main usage of it.
</blockquote></details>

types.h contains the types used for writing a runtime::Program.
As whit3z said, this ValueType is closed and used in only this Value.h and Value.cc.


<!-- Sent from Reviewable.io -->

2022-12-14 05:14 UTC, Naphann reviewed
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446)* status: all files reviewed, 16 unresolved discussions (waiting on @res6idue, @sierpinskiii, and @zigen)

___
*[`quisp/runtime/Value.h` line 20 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBeJjA3kRJzbLac0TN:-NJE2P0d8gmIt3cCPC82:b-agvn00) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Value.h#L20)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

The main difference between struct and class is that struct is a value type while class is reference type. 
All members of struct are exposed as public by default. This can be a problem if we want a read-only value so we need to use class instead.
</blockquote></details>

Please disregard the comment about reference type vs value type. I'm confused about swift not C++... 
The exposure of members argument still stand though.


<!-- Sent from Reviewable.io -->

2022-12-14 05:19 UTC, Naphann approved these changes
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446)* status: all files reviewed, 14 unresolved discussions (waiting on @res6idue, @sierpinskiii, and @zigen)



<!-- Sent from Reviewable.io -->

2022-12-14 06:52 UTC, res6idue requested changes
> Reviewed 2 of 20 files at r1, 4 of 11 files at r5, 4 of 5 files at r6, 1 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446)* status: all files reviewed, 11 unresolved discussions (waiting on @sierpinskiii and @zigen)

___
*[`quisp/runtime/RuleSet.h` line 84 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJEBih_70GNtaT5xEGT:-NJEBih_70GNtaT5xEGU:b-qv57ir) ([raw file](https://github.com/sfc-aqua/quisp/blob/be5309ceebcb283ab647127589e64409c8278d21/quisp/runtime/RuleSet.h#L84)):*
> ```objc
>       : name(name), rules(rules), termination_condition(termination_cond), debugging(debugging) {}
> 
>   /// @brief analizes its rules and instructions to collect informations for execution.
> ```

analizes -> analyzes?


<!-- Sent from Reviewable.io -->

2022-12-14 09:45 UTC, sierpinskiii approved these changes
> Reviewed 4 of 5 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446)* status: all files reviewed, 1 unresolved discussion (waiting on @zigen)

___
*[`quisp/runtime/opcode.h` line 71 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBkp8A0EE5bRbZVdxu:-NJEoU2_6cJHPSqD0N2G:b-ucfknh) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/opcode.h#L71)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

Thanks!
___
*[`quisp/runtime/RuleSet.h` line 20 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBiwnrDzlHhp6TtnG4:-NJExfnyCdoZIt9qLPer:b-54sncc) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/RuleSet.h#L20)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

I understood what whit3z said. Let's keep using std::vector.
thanks you guys.

https://en.cppreference.com/w/cpp/container/deque

> As opposed to std::vector, the elements of a deque are not stored contiguously: typical implementations use a sequence of individually allocated fixed-size arrays, with additional bookkeeping, which means indexed access to deque must perform two pointer dereferences, compared to vector's indexed access which performs only one.
</blockquote></details>

Acknowledged!
___
*[`quisp/runtime/RuleSet.cc` line 28 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBp8oW15wA2aSr6cHV:-NJEx1BpEppjs6PMuOPR:b-lqdha8) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/RuleSet.cc#L28)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

I agree that we could use a better name. `connection_participating_nodes` is better since we refer to the nodes along the connection path. 
Although I don't think the connection setup behaviour should be written inside the code. You should go read up on "two-pass connection setup" in rdv's paper or quisp paper. 
</blockquote></details>

Roger that, will check out the paper.
___
*[`quisp/runtime/Runtime.h` line 265 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBnxDgBr8dDxleyU9h:-NJEx6Zh789c0eMEg9my:b-5oissd) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime.h#L265)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

reviewable is bad at keeping track of resolved comments. In the current RuleSet we only use these set of operations. But yes we can add more.
</blockquote></details>

It would be my pleasure to add them later.
___
*[`quisp/runtime/Runtime_instructions_test.cc` line 34 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBm_qE86w5GDzPk6Oq:-NJEoDZaAFk6uR7Z5mcn:bhy9ot6) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Runtime_instructions_test.cc#L34)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

It'd be better to have a wiki page for how to write tests or update this README.md https://github.com/sfc-aqua/quisp/blob/master/quisp/test_utils/README.md
</blockquote></details>

Will do.
___
*[`quisp/runtime/types.cc` line 1 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJB_ZYiA39bx6NI6gZr:-NJEoGCA9rL_ndXU3FWv:b-6utjlm) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/types.cc#L1)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

Yeah, for the type.h case, it's ambiguous and unclear what the file contains. 
but basically, it's fine to put it on the header file.
I'll add some comments.
</blockquote></details>

Thank you very much!
___
*[`quisp/runtime/Value.h` line 14 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBbJciC9jok4gadj0n:-NJEoLrm3eqg3NCCfzgH:bqrfamp) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Value.h#L14)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

types.h contains the types used for writing a runtime::Program.
As whit3z said, this ValueType is closed and used in only this Value.h and Value.cc.
</blockquote></details>

Understood!
___
*[`quisp/runtime/Value.h` line 20 at r5](https://reviewable.io/reviews/sfc-aqua/quisp/446#-NJBeJjA3kRJzbLac0TN:-NJEoPSK29aS2cdhq0OI:b-8losc5) ([raw file](https://github.com/sfc-aqua/quisp/blob/fd89d4d60238b277dd8744188845a2b39645f15f/quisp/runtime/Value.h#L20)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Please disregard the comment about reference type vs value type. I'm confused about swift not C++... 
The exposure of members argument still stand though.
</blockquote></details>

Thanks for your explanation :-)


<!-- Sent from Reviewable.io -->

2022-12-14 10:28 UTC, Naphann approved these changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/446)* status: all files reviewed, 1 unresolved discussion (waiting on @res6idue)



<!-- Sent from Reviewable.io -->

2022-12-14 12:39 UTC, merged