Rewrite physical behaviour of the BellStateAnalyzer and BSAController
sfc-aqua/quisp pull request #486
Opened 2023-02-05 10:03 UTC by Naphann

# Changes to physical behaviour of the Bell State Analyzer Node and photon emission at Rule Engine

In this PR I rewrote mainly the BSA and the BSAController. 

## Link level generation mechanism

Prior to this PR, the link generation creates a Phi+ state of Bell pair when no error occurs. This does not reflect the reality of linear optics which is the assumption of the hardware used in QuISP. 

This PR changed the behaviour of the link generation to an entanglement swap where the BSA simply measure the incoming photons in Bell basis. The BSA is assume to be able to distinguish between Psi+ and Psi- state where Phi +/- state cannot be distinguish hence even with no loss or channel error. The success probability of the link generation is only at 50%.

The link level message is also changed into denoting a successful measurement instead of the failure.

The BSAController now has a BSMNotification time out which will increase each time QNode does not emit photons. The backoff time scales linearly to the number of no response.

## Photon emission mechanism

Prior to this PR, Rule Engine (RE) relies on multiple packet and internal messages to emit a photon. In this PR, I introduce a new mechanism where upon receiving BSA results. All emission scheduled will be cancelled. And we only schedule one photon emission at a time to the QNIC. The self message only contains `EmitPhoton` message type and each QNIC has one single message maintained by the RE. 

This closes #286 #371 #457

2023-02-05 11:45 UTC, res6idue requested changes
> Reviewed 14 of 86 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: 14 of 86 files reviewed, 1 unresolved discussion (waiting on @Naphann and @zigen)

___
*[`quisp/backends/GraphState/Qubit.cc` line 361 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNWNndnCmMslzjIASsu:-NNWNndnCmMslzjIASsv:bd61xog) ([raw file](https://github.com/sfc-aqua/quisp/blob/cb589057907726fb33c592b3803a555e9f89fa30/quisp/backends/GraphState/Qubit.cc#L361)):*
> ```cpp
> EigenvalueResult GraphStateQubit::graphMeasureZ(const EigenvalueResult eigenvalue) {
>   auto vop = this->vertex_operator;
>   auto result = eigenvalue;
> ```

I think ```result``` is not being used.


<!-- Sent from Reviewable.io -->

2023-02-05 12:32 UTC, Naphann reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: 14 of 86 files reviewed, 1 unresolved discussion (waiting on @res6idue and @zigen)

___
*[`quisp/backends/GraphState/Qubit.cc` line 361 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNWNndnCmMslzjIASsu:-NNWY_3X1E2pafpU7yX1:b-6k5mhf) ([raw file](https://github.com/sfc-aqua/quisp/blob/cb589057907726fb33c592b3803a555e9f89fa30/quisp/backends/GraphState/Qubit.cc#L361)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

I think ```result``` is not being used.
</blockquote></details>

you're right. I'll delete after you and zigen finished with the review.


<!-- Sent from Reviewable.io -->

2023-02-05 13:16 UTC, zigen requested changes
> Reviewed 46 of 86 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: 57 of 86 files reviewed, 3 unresolved discussions (waiting on @Naphann and @res6idue)

___
*[`quisp/networks/topology_linear_network.ned` line 64 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNWhrJLB35Gb3uXd-VK:-NNWhrJLB35Gb3uXd-VL:bbi8wwz) ([raw file](https://github.com/sfc-aqua/quisp/blob/cb589057907726fb33c592b3803a555e9f89fa30/quisp/networks/topology_linear_network.ned#L64)):*
> ```
>             @display("i=COMP");
>         }
>         BSA: BSANodeNode {
> ```

typo: BSANode
___
*[`quisp/test_utils/mock_backends/MockQuantumBackend.h` line 20 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNWgEWD9cWjD0_r2HcD:-NNWgEWD9cWjD0_r2HcE:b-cvcq7j) ([raw file](https://github.com/sfc-aqua/quisp/blob/cb589057907726fb33c592b3803a555e9f89fa30/quisp/test_utils/mock_backends/MockQuantumBackend.h#L20)):*
> ```objc
>   MOCK_METHOD(IBackendQubit *, createOrGetQubit, (const IQubitId *), (override));
>   MOCK_METHOD(void, deleteQubit, (const IQubitId *), (override));
>   MOCK_METHOD(const module_type::SimTime &, getSimTime, (), (override));
> ```

include omnetpp.h and use `omnetpp::SimTime`, not `module_type`


<!-- Sent from Reviewable.io -->

2023-02-05 13:29 UTC, Naphann reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: 54 of 86 files reviewed, 3 unresolved discussions (waiting on @res6idue and @zigen)

___
*[`quisp/backends/GraphState/Qubit.cc` line 361 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNWNndnCmMslzjIASsu:-NNWl5DIBr-puAXULZfg:b-9unw5o) ([raw file](https://github.com/sfc-aqua/quisp/blob/cb589057907726fb33c592b3803a555e9f89fa30/quisp/backends/GraphState/Qubit.cc#L361)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

you're right. I'll delete after you and zigen finished with the review.
</blockquote></details>

deleted
___
*[`quisp/networks/topology_linear_network.ned` line 64 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNWhrJLB35Gb3uXd-VK:-NNWktL35bWHJNKxSXyQ:b-7ql1td) ([raw file](https://github.com/sfc-aqua/quisp/blob/cb589057907726fb33c592b3803a555e9f89fa30/quisp/networks/topology_linear_network.ned#L64)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

typo: BSANode
</blockquote></details>

fixed
___
*[`quisp/test_utils/mock_backends/MockQuantumBackend.h` line 20 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNWgEWD9cWjD0_r2HcD:-NNWku8wA4DCa__Vrkwu:b7xkg6e) ([raw file](https://github.com/sfc-aqua/quisp/blob/cb589057907726fb33c592b3803a555e9f89fa30/quisp/test_utils/mock_backends/MockQuantumBackend.h#L20)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

include omnetpp.h and use `omnetpp::SimTime`, not `module_type`
</blockquote></details>

changed to `omnetpp::simtime_t` 


<!-- Sent from Reviewable.io -->

2023-02-05 16:11 UTC, res6idue reviewed
> Reviewed 18 of 86 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: 74 of 86 files reviewed, 3 unresolved discussions (waiting on @Naphann and @zigen)

___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc` line 218 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNXKc_2D6yXzUcpll3J:-NNXKc_2D6yXzUcpll3K:bssu1kj) ([raw file](https://github.com/sfc-aqua/quisp/blob/d33cb2a6f351592f9afd09712d8db7f407cc6897/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L218)):*
> ```cpp
> 
>   // TODO: make a more sophisticated hash and support emitting multiple photons
>   auto *photon_ref = backend->createOrGetQubit(new QubitId(node_address, qnic_index, 100, stationary_qubit_address));
> ```

why is qnic_type set to 100 in here?


<!-- Sent from Reviewable.io -->

2023-02-05 16:21 UTC, Naphann reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: 74 of 86 files reviewed, 3 unresolved discussions (waiting on @res6idue and @zigen)

___
*[`quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc` line 218 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNXKc_2D6yXzUcpll3J:-NNXMP-1-Mku3FwyjT-s:b-a6gjkb) ([raw file](https://github.com/sfc-aqua/quisp/blob/d33cb2a6f351592f9afd09712d8db7f407cc6897/quisp/modules/QNIC/StationaryQubit/StationaryQubit.cc#L218)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

why is qnic_type set to 100 in here?
</blockquote></details>

It is just a magic number to create a new key for photon qubit. A better way is have backend providing create qubit without a specify key and method for the qubit to be deleted easily without telling the backend directly on what its key is. Also I think backend using pointer as a key is not a good idea and the key should be passed as value and not as pointers. 

I will make an issue to fix this later. Unless you think it is crucial and should be fixed now. 


<!-- Sent from Reviewable.io -->

2023-02-06 02:22 UTC, zigen requested changes
> Reviewed 21 of 86 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: 78 of 86 files reviewed, 2 unresolved discussions (waiting on @Naphann and @res6idue)

___
*[`quisp/modules/PhysicalConnection/BSA/BSA.md` line 1 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNZV6tGAOalhlHq826Y:-NNZV6tGAOalhlHq826Z:b-n29err) ([raw file](https://github.com/sfc-aqua/quisp/blob/d33cb2a6f351592f9afd09712d8db7f407cc6897/quisp/modules/PhysicalConnection/BSA/BSA.md#L1)):*
> ```Markdown
> # Bell State Analyzer
> ```

"README.md" is a better file name because we can see the file when we open this directory on GitHub.
___
*[`quisp/modules/PhysicalConnection/BSA/BSA.md` line 9 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNZVJZQ96dtsqB1aVou:-NNZVJZQ96dtsqB1aVov:bz5wiex) ([raw file](https://github.com/sfc-aqua/quisp/blob/d33cb2a6f351592f9afd09712d8db7f407cc6897/quisp/modules/PhysicalConnection/BSA/BSA.md#L9)):*
> ```Markdown
> The BellStateAnalyzer module is the one processing the photons.
> 
> The BSA works like a state machine. It has 3 states,
> ```

it said 4 in the next sentence... you forgot to remove this?


<!-- Sent from Reviewable.io -->

2023-02-06 02:32 UTC, Naphann reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: 78 of 86 files reviewed, 2 unresolved discussions (waiting on @res6idue and @zigen)

___
*[`quisp/modules/PhysicalConnection/BSA/BSA.md` line 1 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNZV6tGAOalhlHq826Y:-NNZYFNZ77XL7Yk7Pk6j:bc9iqbg) ([raw file](https://github.com/sfc-aqua/quisp/blob/d33cb2a6f351592f9afd09712d8db7f407cc6897/quisp/modules/PhysicalConnection/BSA/BSA.md#L1)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

"README.md" is a better file name because we can see the file when we open this directory on GitHub.
</blockquote></details>

Oh actually I forgot to finish this file, I'm not sure if it should be here or in other place. I haven't finished writing it...
I also didn't intend to push the pseudo code python file as well. That could be combined into this file. 

I'll clean this file up and remove the pseudocode file.
___
*[`quisp/modules/PhysicalConnection/BSA/BSA.md` line 9 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNZVJZQ96dtsqB1aVou:-NNZYZHa7-3miCnJNX2V:b27n7cm) ([raw file](https://github.com/sfc-aqua/quisp/blob/d33cb2a6f351592f9afd09712d8db7f407cc6897/quisp/modules/PhysicalConnection/BSA/BSA.md#L9)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

it said 4 in the next sentence... you forgot to remove this?
</blockquote></details>

Refer to above comment. Maybe I should at least write a basic idea of this. 


<!-- Sent from Reviewable.io -->

2023-02-06 02:43 UTC, zigen requested changes
> Reviewed 5 of 86 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: 79 of 86 files reviewed, 4 unresolved discussions (waiting on @Naphann and @res6idue)

___
*[`quisp/modules/PhysicalConnection/BSA/BSA.md` line 1 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNZV6tGAOalhlHq826Y:-NNZ_iHBAfcfI5D9RG4F:bjue848) ([raw file](https://github.com/sfc-aqua/quisp/blob/d33cb2a6f351592f9afd09712d8db7f407cc6897/quisp/modules/PhysicalConnection/BSA/BSA.md#L1)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Oh actually I forgot to finish this file, I'm not sure if it should be here or in other place. I haven't finished writing it...
I also didn't intend to push the pseudo code python file as well. That could be combined into this file. 

I'll clean this file up and remove the pseudocode file.
</blockquote></details>

oh okay.
___
*[`quisp/modules/PhysicalConnection/BSA/BSAController.cc` line 150 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNZaUO6Cp082EdfUllM:-NNZaUO6Cp082EdfUllN:bc7kwz3) ([raw file](https://github.com/sfc-aqua/quisp/blob/d33cb2a6f351592f9afd09712d8db7f407cc6897/quisp/modules/PhysicalConnection/BSA/BSAController.cc#L150)):*
> ```cpp
>   // this BSAController is inside QNIC_R but the port is connecting to outside
>   if (port != 0 && strcmp(getParentModule()->getName(), "qnic_r") == 0) {
>     auto *bsa = getParentModule()->getSubmodule("bsa");
> ```

you don't need this, plz remove it.
___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 94 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNZZvwA0heig8-IHgh5:-NNZZvwA0heig8-IHgh6:bscsnr4) ([raw file](https://github.com/sfc-aqua/quisp/blob/d33cb2a6f351592f9afd09712d8db7f407cc6897/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L94)):*
> ```cpp
>     auto qubit_index = qnic_store->takeFreeQubitIndex(type, qnic_index);
> 
>     if (number_of_free_emitters == 0) return;
> ```

I think we should delete the `msg` 


<!-- Sent from Reviewable.io -->

2023-02-06 02:57 UTC, zigen requested changes
> Reviewed 11 of 86 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: all files reviewed, 5 unresolved discussions (waiting on @Naphann)

___
*[`quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.h` line 10 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNZdL7oDrJTVFlbcX_W:-NNZdL7oDrJTVFlbcX_X:b3z0rae) ([raw file](https://github.com/sfc-aqua/quisp/blob/d33cb2a6f351592f9afd09712d8db7f407cc6897/quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.h#L10)):*
> ```objc
> #include "omnetpp/simtime_t.h"
> 
> using namespace quisp::physical::types;
> ```

I don't recommend to use `using namespace` in header file because of namespace pollution.
put it into the BellStateAnalyzer.cc file


<!-- Sent from Reviewable.io -->

2023-02-06 06:00 UTC, res6idue reviewed
> Reviewed 21 of 86 files at r1, 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: all files reviewed, 5 unresolved discussions (waiting on @Naphann)



<!-- Sent from Reviewable.io -->

2023-02-06 06:09 UTC, res6idue reviewed
> Reviewed 10 of 86 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: all files reviewed, 5 unresolved discussions (waiting on @Naphann)



<!-- Sent from Reviewable.io -->

2023-02-06 06:09 UTC, res6idue reviewed
> Reviewed 1 of 86 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: all files reviewed, 5 unresolved discussions (waiting on @Naphann)



<!-- Sent from Reviewable.io -->

2023-02-06 06:10 UTC, Naphann reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: all files reviewed, 5 unresolved discussions (waiting on @zigen)

___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 94 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNZZvwA0heig8-IHgh5:-NN_KjXuDlwGBY3EJK4s:b2suywr) ([raw file](https://github.com/sfc-aqua/quisp/blob/d33cb2a6f351592f9afd09712d8db7f407cc6897/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L94)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

I think we should delete the `msg` 
</blockquote></details>

The EmitPhoton message is a self-timer message store in the map `emit_photon_timer_map`. And is always reuse for the same QNIC. We only delete it in the destructor of RuleEngine. 


<!-- Sent from Reviewable.io -->

2023-02-06 06:19 UTC, zigen reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: all files reviewed, 3 unresolved discussions (waiting on @Naphann)

___
*[`quisp/modules/QRSA/RuleEngine/RuleEngine.cc` line 94 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNZZvwA0heig8-IHgh5:-NN_N9cm4dfS3PQtS6Zx:buctnmt) ([raw file](https://github.com/sfc-aqua/quisp/blob/d33cb2a6f351592f9afd09712d8db7f407cc6897/quisp/modules/QRSA/RuleEngine/RuleEngine.cc#L94)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

The EmitPhoton message is a self-timer message store in the map `emit_photon_timer_map`. And is always reuse for the same QNIC. We only delete it in the destructor of RuleEngine. 
</blockquote></details>

ah got it. 


<!-- Sent from Reviewable.io -->

2023-02-06 08:28 UTC, Naphann reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: 80 of 87 files reviewed, 3 unresolved discussions (waiting on @res6idue and @zigen)

___
*[`quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.h` line 10 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNZdL7oDrJTVFlbcX_W:-NN_pfrdDSOhHSlobgRJ:b6p80q5) ([raw file](https://github.com/sfc-aqua/quisp/blob/d33cb2a6f351592f9afd09712d8db7f407cc6897/quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.h#L10)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

I don't recommend to use `using namespace` in header file because of namespace pollution.
put it into the BellStateAnalyzer.cc file
</blockquote></details>

removed. 
___
*[`quisp/modules/PhysicalConnection/BSA/BSAController.cc` line 150 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNZaUO6Cp082EdfUllM:-NN_LDEeEnCm6X4l92As:b-hfpv0l) ([raw file](https://github.com/sfc-aqua/quisp/blob/d33cb2a6f351592f9afd09712d8db7f407cc6897/quisp/modules/PhysicalConnection/BSA/BSAController.cc#L150)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

you don't need this, plz remove it.
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2023-02-06 08:56 UTC, res6idue reviewed
> Reviewed 1 of 86 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: 80 of 87 files reviewed, 3 unresolved discussions (waiting on @Naphann and @zigen)



<!-- Sent from Reviewable.io -->

2023-02-06 09:01 UTC, zigen approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486#-:-NN_xOTO9qLAppJc_DN6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Naphann)



<!-- Sent from Reviewable.io -->

2023-02-06 13:38 UTC, res6idue requested changes
> Reviewed 1 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: all files reviewed, 6 unresolved discussions (waiting on @Naphann)

___
*[`quisp/modules/PhysicalConnection/BSA/README.md` line 8 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNavO1G-KI4NuP51Pvc:-NNavO1G-KI4NuP51Pvd:b-cx80da) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/PhysicalConnection/BSA/README.md#L8)):*
> ```Markdown
> 
> BSA component in QuISP comprises of two modules, the BellStateAnalyzer and the BSAController.
> BellStateAnalyzer is the physical module where it only concern itself with measuring the photons coming from the two ports.
> ```

concern -> concerns?
___
*[`quisp/modules/PhysicalConnection/BSA/README.md` line 9 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNavXGS2tqlRR2SrUky:-NNavXGS2tqlRR2SrUkz:b-sk1ggd) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/PhysicalConnection/BSA/README.md#L9)):*
> ```Markdown
> BSA component in QuISP comprises of two modules, the BellStateAnalyzer and the BSAController.
> BellStateAnalyzer is the physical module where it only concern itself with measuring the photons coming from the two ports.
> BSAController on the other hand, handles the messaging and signalling of neighbour QNode(s), sending measurement results and tell them when the first photon should arrive.
> ```

tell -> telling?
___
*[`quisp/modules/PhysicalConnection/BSA/README.md` line 14 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNavq96E-nmgScL7Nr1:-NNavq970UdIjH2A7Th7:b-bixw61) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/PhysicalConnection/BSA/README.md#L14)):*
> ```Markdown
> Its functionality stays the same whether it lives inside a QNIC or a BSANode.
> The only difference between internal (inside QNode) or external (inside BSANode) is the initialization phase inside the BSAController.
> The module heirachy traversal to find the incoming channel and which nodes this BSAController should talk to is different.
> ```

heirachy -> hierarchy ?
___
*[`quisp/modules/PhysicalConnection/BSA/README.md` line 18 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNavxUACpm0XAuJQJkl:-NNavxUACpm0XAuJQJkm:b4cg9d6) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/PhysicalConnection/BSA/README.md#L18)):*
> ```Markdown
> ## How BellStateAnalyzer Module works
> 
> The BellStateAnalyzer manage its behaviour using a state machine. It has 4 states namely; `idle`, `accepting`, `accepting_left`, `accepting_right`.
> ```

manage -> manages?
___
*[`quisp/modules/PhysicalConnection/BSA/README.md` line 19 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNawMTCA-EDDptorw6k:-NNawMTCA-EDDptorw6l:b6vvx2a) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/PhysicalConnection/BSA/README.md#L19)):*
> ```Markdown
> 
> The BellStateAnalyzer manage its behaviour using a state machine. It has 4 states namely; `idle`, `accepting`, `accepting_left`, `accepting_right`.
> Currently, it caches all the photons coming in from both sides until last photons from both side arrive.
> ```

both side -> both sides?
___
*[`quisp/modules/PhysicalConnection/BSA/README.md` line 20 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNaw7gr-ugcI9ncYQvc:-NNaw7gr-ugcI9ncYQvd:b-w165dn) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/PhysicalConnection/BSA/README.md#L20)):*
> ```Markdown
> The BellStateAnalyzer manage its behaviour using a state machine. It has 4 states namely; `idle`, `accepting`, `accepting_left`, `accepting_right`.
> Currently, it caches all the photons coming in from both sides until last photons from both side arrive.
> Then it compiles the results in batches and signal to BSAController which then send it to QNodes.
> ```

signal -> signals?
send -> sends?


<!-- Sent from Reviewable.io -->

2023-02-06 14:25 UTC, res6idue requested changes
> Reviewed 8 of 86 files at r1, 3 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: all files reviewed, 9 unresolved discussions (waiting on @Naphann)

___
*[`quisp/modules/QNIC.ned` line 77 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNazDwAA7heJ0tih6uv:-NNazDwAA7heJ0tih6uw:b-hq0j1u) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/QNIC.ned#L77)):*
> ```
> 
> 
>         // // If no BSA is inside the node
> ```

Are these comments necessary?
___
*[`quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc` line 10 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNb1FC7AwnSaYr6MpaP:-NNb1FC7AwnSaYr6MpaQ:b3bfyg9) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc#L10)):*
> ```cpp
> #include <stdexcept>
> #include <vector>
> #include "backends/GraphState/Qubit.h"
> ```

Why are we including this backend?
___
*[`quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc` line 187 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNb0yLz9YnaI-PZRLjZ:-NNb0yLz9YnaI-PZRLj_:b-3wbe64) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc#L187)):*
> ```cpp
>     p_ref->noiselessZ();
>   }
>   q_ref->gateCNOT(p_ref);
> ```

Why are we using the noisy cnot gate here?


<!-- Sent from Reviewable.io -->

2023-02-06 14:26 UTC, res6idue requested changes
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: all files reviewed, 9 unresolved discussions (waiting on @Naphann)

___
*[`quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc` line 10 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNb1FC7AwnSaYr6MpaP:-NNb6cmX15kgJBoDP6Tc:b7d9t52) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc#L10)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

Why are we including this backend?
</blockquote></details>

I mean, why not the qubit interface?


<!-- Sent from Reviewable.io -->

2023-02-06 14:53 UTC, res6idue requested changes
> Reviewed 1 of 86 files at r1, 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: all files reviewed, 11 unresolved discussions (waiting on @Naphann)

___
*[`quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.h` line 35 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNb9Ktw6NwyLl_hnYvr:-NNb9Ktw6NwyLl_hnYvs:b-l6zyxf) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.h#L35)):*
> ```objc
> 
>  private:
>   void registerClickBatches();
> ```

I can't find this being used in BellStateAnalyzer.cc
___
*[`quisp/modules/PhysicalConnection/BSA/BSAController.h` line 47 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNb9ZV0CtIJS0fGGT57:-NNb9ZV0CtIJS0fGGT58:bnsixz2) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/PhysicalConnection/BSA/BSAController.h#L47)):*
> ```objc
>   int getExternalAdressFromPort(int port);
>   void cancelBSMTimeOut();
>   void registerClickBatches(std::vector<BSAClickResult>& results);
> ```

Where is this function used? Can we remove it?


<!-- Sent from Reviewable.io -->

2023-02-06 14:58 UTC, res6idue reviewed
> Reviewed 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: all files reviewed, 11 unresolved discussions (waiting on @Naphann)



<!-- Sent from Reviewable.io -->

2023-02-06 15:15 UTC, res6idue reviewed
> Reviewed 1 of 86 files at r1, 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: all files reviewed, 11 unresolved discussions (waiting on @Naphann)



<!-- Sent from Reviewable.io -->

2023-02-06 16:40 UTC, Naphann reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486)* status: 85 of 87 files reviewed, 11 unresolved discussions (waiting on @res6idue and @zigen)

___
*[`quisp/modules/QNIC.ned` line 77 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNazDwAA7heJ0tih6uv:-NNbVlbv0pwdouljEVsY:b-9unw5o) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/QNIC.ned#L77)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

Are these comments necessary?
</blockquote></details>

deleted
___
*[`quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.h` line 35 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNb9Ktw6NwyLl_hnYvr:-NNbX2zpBay2ndtxH9tx:b-hzz4qd) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.h#L35)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

I can't find this being used in BellStateAnalyzer.cc
</blockquote></details>

you're right. deleted
___
*[`quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc` line 10 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNb1FC7AwnSaYr6MpaP:-NNbZ1lX7iY8MCuU89mb:b2srtgx) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc#L10)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

I mean, why not the qubit interface?
</blockquote></details>

right, it was auto-imported by the VSCode so I didn't check that. changed.
___
*[`quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc` line 187 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNb0yLz9YnaI-PZRLjZ:-NNbZywQ81MVv-nBgBj6:buxqio5) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc#L187)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

Why are we using the noisy cnot gate here?
</blockquote></details>

good catch. fixed
___
*[`quisp/modules/PhysicalConnection/BSA/BSAController.h` line 47 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNb9ZV0CtIJS0fGGT57:-NNb_Q89AmxLrVFnRk6x:b-9unw5o) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/PhysicalConnection/BSA/BSAController.h#L47)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

Where is this function used? Can we remove it?
</blockquote></details>

deleted
___
*[`quisp/modules/PhysicalConnection/BSA/README.md` line 8 at r3](https://reviewable.io/reviews/sfc-aqua/quisp/486#-NNavO1G-KI4NuP51Pvc:-NNb_spD3Tt5EuX8FxzG:b32ipab) ([raw file](https://github.com/sfc-aqua/quisp/blob/ff38b80075469997c7bc3ca2b6125eedefb9a5c5/quisp/modules/PhysicalConnection/BSA/README.md#L8)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

concern -> concerns?
</blockquote></details>

fixed all the grammars.


<!-- Sent from Reviewable.io -->

2023-02-06 16:46 UTC, res6idue approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486#-:-NNbbf7d9YXU_TeHaluF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Naphann)



<!-- Sent from Reviewable.io -->

2023-02-06 16:56 UTC, res6idue approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/486#-:-NNbe3IG0y-GePYx68Nu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Naphann)



<!-- Sent from Reviewable.io -->

2023-02-06 17:24 UTC, merged