Delete QNIC_id struct
sfc-aqua/quisp pull request #503
Opened 2023-02-24 09:56 UTC by zigen

`QNIC_id` was used in RoutingDaemon, but it only uses `QNIC_id.address` (this means self_qnic_address).

2023-03-05 13:00 UTC, zigen reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/503)* status: 0 of 5 files reviewed, all discussions resolved

___
*[`quisp/modules/QNIC.h` line 41 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/503#-NPlqGfn2DnTVgCvSktL:-NPlqGfn2DnTVgCvSktM:bvp37sr) ([raw file](https://github.com/sfc-aqua/quisp/blob/726f00e6532205e79894dff40233239419e87e32/quisp/modules/QNIC.h#L41)):*
> ```objc
>   int address;
>   bool isReserved;
> } QNIC_id;
> ```

FYI, delete this QNIC_id and define the QNIC.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.h` line 25 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/503#-NPlqXJ7AeONih6D7uIm:-NPlqXJ7AeONih6D7uIn:b21dreg) ([raw file](https://github.com/sfc-aqua/quisp/blob/726f00e6532205e79894dff40233239419e87e32/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.h#L25)):*
> ```objc
>  protected:
>   int myAddress;
>   typedef std::map<int, QNIC> RoutingTable;  // destaddr -> {gate_index (We need this to access qnic, but it is not unique because we have 3 types of qnics), qnic_address (unique)}
> ```

FYI, only the `QNIC.address` was used in RoutingTable.


<!-- Sent from Reviewable.io -->

2023-03-05 15:10 UTC, Naphann requested changes
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/503)* status: all files reviewed, 4 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[`quisp/modules/QNIC.h` line 45 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/503#-NPmIPlS2p3oQg-uvNin:-NPmIPlS2p3oQg-uvNio:b1c6l9n) ([raw file](https://github.com/sfc-aqua/quisp/blob/5f53c6123fea76297cf160aff2184260f5767aaa/quisp/modules/QNIC.h#L45)):*
> ```objc
> };
> 
> struct QNIC_pair_info {
> ```

Should we use the naming convention `QNICPairInfo`? 
___
*[`quisp/modules/QNIC.h` line 46 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/503#-NPmIZNM4weL9wXtbrcd:-NPmIZNM4weL9wXtbrce:b-28pawp) ([raw file](https://github.com/sfc-aqua/quisp/blob/5f53c6123fea76297cf160aff2184260f5767aaa/quisp/modules/QNIC.h#L46)):*
> ```objc
> 
> struct QNIC_pair_info {
>   QNIC fst;
> ```

`first` and `second` instead? It's not that longer 
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.h` line 32 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/503#-NPmIqWwD5RQiAs1I0Dw:-NPmIqWwD5RQiAs1I0Dx:b6f51gh) ([raw file](https://github.com/sfc-aqua/quisp/blob/5f53c6123fea76297cf160aff2184260f5767aaa/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.h#L32)):*
> ```objc
> 
>   void generateRoutingTable(cTopology* topo);
>   int getQNicAddr(const cGate* const parentModuleGate);
> ```

I think we should normalize the convention, do we use `QNic` or `QNIC`. I prefer caps on abbreviations so `QNIC` but I'm open to otherwise. 
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 8 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/503#-NPmJC2Y8khva9d5MKyH:-NPmJC2ZDEDBol78h27X:b-pw9d6p) ([raw file](https://github.com/sfc-aqua/quisp/blob/5f53c6123fea76297cf160aff2184260f5767aaa/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L8)):*
> ```cpp
> #include "RoutingDaemon.h"
> #include <messages/classical_messages.h>
> #include <vector>
> ```

can you reorganize the import?

```
#include "RoutingDaemon.h"

#include <vector>
// space here or not is optional I guess 
#include "message/classical_messages.h"
```


<!-- Sent from Reviewable.io -->

2023-03-06 03:36 UTC, zigen reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/503)* status: all files reviewed, 4 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[`quisp/modules/QNIC.h` line 45 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/503#-NPmIPlS2p3oQg-uvNin:-NPmNEeTEqGya6gXEQNO:b-8ahr7w) ([raw file](https://github.com/sfc-aqua/quisp/blob/5f53c6123fea76297cf160aff2184260f5767aaa/quisp/modules/QNIC.h#L45)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

Should we use the naming convention `QNICPairInfo`? 
</blockquote></details>

ah, I want to make it `std::pair<QNic, QNic>`
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.h` line 32 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/503#-NPmIqWwD5RQiAs1I0Dw:-NPmM9pj-DBRfMNM2dlI:b-ujq29x) ([raw file](https://github.com/sfc-aqua/quisp/blob/5f53c6123fea76297cf160aff2184260f5767aaa/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.h#L32)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

I think we should normalize the convention, do we use `QNic` or `QNIC`. I prefer caps on abbreviations so `QNIC` but I'm open to otherwise. 
</blockquote></details>

I prefer `QNic`, because of readability, for example: `QNICId` vs `QNicId`, or `QNICType` vs `QNicType`. 
the caps on abbreviation is fine but I don't want to make names like `QNIC_id` or `QNIC_type`...


<!-- Sent from Reviewable.io -->

2023-03-06 03:51 UTC, zigen reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/503)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 8 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/503#-NPmJC2Y8khva9d5MKyH:-NPp1szY46XgYeVz4Yb-:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/5f53c6123fea76297cf160aff2184260f5767aaa/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L8)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

can you reorganize the import?

```
#include "RoutingDaemon.h"

#include <vector>
// space here or not is optional I guess 
#include "message/classical_messages.h"
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-06 04:43 UTC, zigen reviewed
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/503)* status: 3 of 12 files reviewed, 4 unresolved discussions (waiting on @Chibikuri and @Naphann)

___
*[`quisp/modules/QNIC.h` line 46 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/503#-NPmIZNM4weL9wXtbrcd:-NPpDYTa5S4gOpam_wF2:bqz7evn) ([raw file](https://github.com/sfc-aqua/quisp/blob/5f53c6123fea76297cf160aff2184260f5767aaa/quisp/modules/QNIC.h#L46)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

`first` and `second` instead? It's not that longer 
</blockquote></details>

now we can access it with `first` and `second`


<!-- Sent from Reviewable.io -->

2023-03-06 13:36 UTC, merged