Implement simple OSPF
sfc-aqua/quisp pull request #526
Opened 2023-06-07 14:49 UTC by Tatzhiro

2023-06-08 05:23 UTC, zigen reviewed
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @Tatzhiro)

___
*[`.vscode/launch.json` line 29 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NXOQx-h0RGhj_R51TtP:-NXOQx-h0RGhj_R51TtQ:b-qlo7hj) ([raw file](https://github.com/sfc-aqua/quisp/blob/cd698558c2609ec6b52f548efd2946e871c2bf4a/.vscode/launch.json#L29)):*
> ```JSON
>                 "Cmdenv",
>                 "-c",
>                 "Entanglement_Swapping_MM_3_Nodes"
> ```

add another task. this change affects everyone so for your specific case, you should not change the tasks.
___
*[`quisp/modules/Common/Router.h` line 6 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NXORMyd2sGOffHPKmSw:-NXORMyd2sGOffHPKmSx:b4d0chw) ([raw file](https://github.com/sfc-aqua/quisp/blob/cd698558c2609ec6b52f548efd2946e871c2bf4a/quisp/modules/Common/Router.h#L6)):*
> ```objc
> #include <map>
> #include "messages/base_messages_m.h"
> #include "messages/ospf_messages_m.h"
> ```

use `quisp/messages/classical_messages.h`


<!-- Sent from Reviewable.io -->

2023-06-11 09:55 UTC, Tatzhiro reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @zigen)

___
*[`.vscode/launch.json` line 29 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NXOQx-h0RGhj_R51TtP:-NXds4GI0gSwVFxJYAs-:b6ba3c1) ([raw file](https://github.com/sfc-aqua/quisp/blob/cd698558c2609ec6b52f548efd2946e871c2bf4a/.vscode/launch.json#L29)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

add another task. this change affects everyone so for your specific case, you should not change the tasks.
</blockquote></details>

Sorry I forgot to undo the changes in this file. I will fix it once I finish my draft.
___
*[`quisp/modules/Common/Router.h` line 6 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NXORMyd2sGOffHPKmSw:-NXdsHwP1tjXNtmSFu4m:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/cd698558c2609ec6b52f548efd2946e871c2bf4a/quisp/modules/Common/Router.h#L6)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

use `quisp/messages/classical_messages.h`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-29 05:59 UTC, Chibikuri requested changes
> Reviewed 1 of 9 files at r2, 1 of 7 files at r4, 2 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 4 of 13 files reviewed, 4 unresolved discussions (waiting on @Tatzhiro and @zigen)

___
*[`quisp/modules/Common/Router.h` line 44 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NZ4gFrd8R2vk5DvUexg:-NZ4gFrd8R2vk5DvUexh:badljv4) ([raw file](https://github.com/sfc-aqua/quisp/blob/b8341767e39bc54d1b9d0a839e3aa8e529c074f4/quisp/modules/Common/Router.h#L44)):*
> ```objc
>    *          Slave sends its Summary LSDB to Master
>    *          Master send empty DBD packet until it receives Summary LSDB from Slave
>    */
> ```

Instead of leaving comments on the header file, it would be useful to leave some comments like this in the source file. 
___
*[`quisp/test_utils/Channel.cc` line 8 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NZ4fQS50qJ5ZRB5dGnD:-NZ4fQS50qJ5ZRB5dGnE:bjjj176) ([raw file](https://github.com/sfc-aqua/quisp/blob/b8341767e39bc54d1b9d0a839e3aa8e529c074f4/quisp/test_utils/Channel.cc#L8)):*
> ```cpp
> TestDatarateChannel::TestDatarateChannel() : cDatarateChannel() { setCost(); }
> 
> void TestDatarateChannel::setCost(double cost) {
> ```

I assume this is a test for cost calculation in OSPF, right?
I guess the cost used in the OSPF link cost calculation should be taken from Hardware Monitor. 
Hardware monitor first runs a tomography (or something else) to know the link cost and that information is informed to the routing daemon.


<!-- Sent from Reviewable.io -->

2023-06-29 06:03 UTC, Chibikuri commented
@Tatzhiro I'd like to apologize that the naming of components in QuISP is very confusing. I guess the right place you implement your code is not on Router.cc, but on RoutingDaemon...
The Router under the common module is just receiving messages from outside and distributing them to components (and vice versa). Since the thing you're working on is more than that, your code should be working as a daemon process that communicates with other node and establish a topology map and so on.

2023-06-30 01:43 UTC, Tatzhiro reviewed
Router also has a role in receiving messages from other components within the same node, and then sending those messages to other nodes by referring to the routing table. 
The thing that I worked on in this pull request is to simply create a routing table dynamically. 
Do you mean Router module does not need dynamic routing table generation, and only RoutingDaemon needs it?

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526#-:-NZ8sgBs5MgLHcOz2bpB:bc76rl2)* status: 4 of 13 files reviewed, 4 unresolved discussions (waiting on @Chibikuri, @Tatzhiro, and @zigen)

___
*[`quisp/modules/Common/Router.h` line 44 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NZ4gFrd8R2vk5DvUexg:-NZ8xbSxB3ygdU7UlxBg:bebrt1w) ([raw file](https://github.com/sfc-aqua/quisp/blob/b8341767e39bc54d1b9d0a839e3aa8e529c074f4/quisp/modules/Common/Router.h#L44)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Instead of leaving comments on the header file, it would be useful to leave some comments like this in the source file. 
</blockquote></details>

Will do
___
*[`quisp/test_utils/Channel.cc` line 8 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NZ4fQS50qJ5ZRB5dGnD:-NZ8vJ6bAEW5WhfACCjp:b5zri8c) ([raw file](https://github.com/sfc-aqua/quisp/blob/b8341767e39bc54d1b9d0a839e3aa8e529c074f4/quisp/test_utils/Channel.cc#L8)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

I assume this is a test for cost calculation in OSPF, right?
I guess the cost used in the OSPF link cost calculation should be taken from Hardware Monitor. 
Hardware monitor first runs a tomography (or something else) to know the link cost and that information is informed to the routing daemon.
</blockquote></details>

For Router.cc, I never used the link cost calculated from the tomography. I used TestDatarateChannel to mock the cost of ClassicalChannel.
I think HardwareMonitor does not provide cost information about ClassicalChannel.
What do you think?
___
*[`.vscode/launch.json` line 29 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NXOQx-h0RGhj_R51TtP:-NZ8xpW81s2GuI0KzTZP:bb6un1j) ([raw file](https://github.com/sfc-aqua/quisp/blob/cd698558c2609ec6b52f548efd2946e871c2bf4a/.vscode/launch.json#L29)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

Sorry I forgot to undo the changes in this file. I will fix it once I finish my draft.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-30 06:44 UTC, Chibikuri commented
RoutingDaemon is the component responsible for generating, and updating the routing table. Router.cc could refer to the routing table existing in Routing Daemon, but Router is not the one that is responsible for routing table generation.

2023-06-30 06:47 UTC, Chibikuri requested changes
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 4 of 13 files reviewed, 4 unresolved discussions (waiting on @Tatzhiro and @zigen)

___
*[`quisp/test_utils/Channel.cc` line 8 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NZ4fQS50qJ5ZRB5dGnD:-NZA25ZzAsZ_1cPd7XYX:b-pqcz5w) ([raw file](https://github.com/sfc-aqua/quisp/blob/b8341767e39bc54d1b9d0a839e3aa8e529c074f4/quisp/test_utils/Channel.cc#L8)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

For Router.cc, I never used the link cost calculated from the tomography. I used TestDatarateChannel to mock the cost of ClassicalChannel.
I think HardwareMonitor does not provide cost information about ClassicalChannel.
What do you think?
</blockquote></details>

Ah, I see. So you're trying to implement an entirely classical OSPF, not a quantum OSPF?


<!-- Sent from Reviewable.io -->

2023-07-01 01:16 UTC, Tatzhiro reviewed
Even before this pull request, Router.cc was generating routing table (I think for classical channels). RoutingDaemon also generates routing table, but it uses quantum channel information to build the table.

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526#-:-NZE-sSm0CbhFNgJWboR:b-wmi19v)* status: 4 of 13 files reviewed, 4 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[`quisp/test_utils/Channel.cc` line 8 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NZ4fQS50qJ5ZRB5dGnD:-NZE-qMwDLWTgH8yrcvE:b-87rmoq) ([raw file](https://github.com/sfc-aqua/quisp/blob/b8341767e39bc54d1b9d0a839e3aa8e529c074f4/quisp/test_utils/Channel.cc#L8)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Ah, I see. So you're trying to implement an entirely classical OSPF, not a quantum OSPF?
</blockquote></details>

That is correct.


<!-- Sent from Reviewable.io -->

2023-07-01 02:02 UTC, Chibikuri commented
> Even before this pull request, Router.cc was generating routing table (I think for classical channels). RoutingDaemon also generates routing table, but it uses quantum channel information to build the table.
> 
> > _[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526#-:-NZE-sSm0CbhFNgJWboR:b-wmi19v)_ status: 4 of 13 files reviewed, 4 unresolved discussions (waiting on @Chibikuri and @zigen)
> 
> _[`quisp/test_utils/Channel.cc` line 8 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NZ4fQS50qJ5ZRB5dGnD:-NZE-qMwDLWTgH8yrcvE:b-87rmoq) ([raw file](https://github.com/sfc-aqua/quisp/blob/b8341767e39bc54d1b9d0a839e3aa8e529c074f4/quisp/test_utils/Channel.cc#L8)):_
> 
> Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…
> That is correct.

@zigen @Naphann What do you think? Do we need classical OSPF here? My initial thought was routing cost was a link cost calculated by hardware monitor, but I might be wrong.

2023-07-01 02:24 UTC, Chibikuri commented
One more point is that the classical path and quantum path must be the same in RuleSet scheme. So if we get different path in quantum and classical, it might be a problem in the simulation.

2023-07-01 03:11 UTC, Naphann commented
@Chibikuri I haven't read the whole thread but as for the one you pinged.

The classical path and quantum path need not be the same. Each node needs to keep track of the next node in the quantum path and send the message to the correct node. So, classical and quantum can be different as long as the message is sent to the next quantum hop for the connection setup process to work.

As for the classical OSPF, I don't think we need it.

2023-07-04 04:38 UTC, Tatzhiro reviewed
@Chibikuri @Naphann 
I see that we don't need classical OSPF and we only need routing protocols to generate routing table in RoutingDaemon based on quantum channels. I can copy and paste the OSPF protocol to RoutingDaemon then. As for the classical OSPF that I implemented in Router.cc, should I remove it entirely from Router.cc, or leave an option to use classical OSPF if needed?
I have the option prepared so the users can choose to run classical OSPF, or fetch the pregenerated classical routing table.
https://github.com/sfc-aqua/quisp/pull/526/files#diff-38f4be36ba6c6b6a3f273b6bafa3f19a4800a86f0acd79fba6e16b0055990397R21

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526#-:-NZUACSB7avlDAz9TjjG:b-ofvfdn)* status: 4 of 13 files reviewed, 4 unresolved discussions (waiting on @Naphann and @zigen)



<!-- Sent from Reviewable.io -->

2023-07-04 04:42 UTC, Chibikuri commented
@Tatzhiro What you can do is just moving your code to Routing daemon. Your implementation itself seems correct and it can be reused  in quantum version by changing cost calculation (not claasical bandwidth but quantum link generation rate)

2023-07-13 03:45 UTC, Chibikuri requested changes
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 2 of 20 files reviewed, 6 unresolved discussions (waiting on @Naphann, @Tatzhiro, and @zigen)

___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 160 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CLQAK3DRT5PANg5yv:-N_CLQAK3DRT5PANg5yw:bp0j0p3) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L160)):*
> ```cpp
> 
>   if (auto pk = dynamic_cast<OspfLsAckPacket *>(msg)) {
>     return;
> ```

Does this do nothing?
___
*[`quisp/modules/Common/LinkStateRoutingProtocol/Ospf.cc` line 3 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CKilE97-jXBN5k_FP:-N_CKilE97-jXBN5k_FQ:brb0rgz) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/Common/LinkStateRoutingProtocol/Ospf.cc#L3)):*
> ```cpp
> #include "Ospf.h"
> 
> namespace quisp::modules::ospf {
> ```

You could move ospf files under routing_daemon/routing_protocols/ or something like that. That would be easy for us to see they are used in routing daemon.


<!-- Sent from Reviewable.io -->

2023-07-13 03:58 UTC, Chibikuri requested changes
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 2 of 20 files reviewed, 8 unresolved discussions (waiting on @Naphann, @Tatzhiro, and @zigen)

___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 352 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CO3ug0utszKMaQw8e:-N_CO3ug0utszKMaQw8f:bj8h9yu) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L352)):*
> ```cpp
>   ospfUpdateLinkStateDatabase(pk);
>   ospfSendUpdatedLsdbToNeighboringRouters(pk->getSrcAddr());
>   generateRoutingTable();
> ```

Why the routing table is generated here not in initialization? I haven't looked at it closely, but every time Lsu packet arrives, create a new routing table?
___
*[`quisp/test_utils/Channel.h` line 20 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CM0qT-R5J6t8BPbE5:-N_CM0qT-R5J6t8BPbE6:bak0h19) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/test_utils/Channel.h#L20)):*
> ```objc
> using omnetpp::internal::cParImpl;
> 
> class TestDatarateChannel : public omnetpp::cDatarateChannel {
> ```

You could remove this since we don't care classical cost here?


<!-- Sent from Reviewable.io -->

2023-07-13 04:07 UTC, Chibikuri requested changes
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 2 of 20 files reviewed, 9 unresolved discussions (waiting on @Naphann, @Tatzhiro, and @zigen)

___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 160 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CLQAK3DRT5PANg5yv:-N_CPSt02so4EnnS7FQD:b-lh1rsh) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L160)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Does this do nothing?
</blockquote></details>

Seems `ospfHandleLinkStateUpdate` handling ack packet?
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 176 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CQSFO6GtdKaJM5VW4:-N_CQSFO6GtdKaJM5VW5:b-whq7kj) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L176)):*
> ```cpp
>   const int src = pk->getSrcAddr();
> 
>   if (ospfMyAddressIsRecognizedByNeighbor(pk) == false && ospfNeighborIsRegistered(src)) {
> ```

Can we combine these statements?

e.g. 
```cpp
if (!ospfMyAddressIsRecognizedByNeighbor(pk) && ospfNeighborIsRegistered(src)) {
   error ()
}else{
 if ...
}
```


<!-- Sent from Reviewable.io -->

2023-07-13 04:37 UTC, Chibikuri requested changes
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 2 of 20 files reviewed, 11 unresolved discussions (waiting on @Naphann, @Tatzhiro, and @zigen)

___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 195 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CRGki1RQ9kO_7bIkh:-N_CRGki1RQ9kO_7bIki:bxtfs5b) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L195)):*
> ```cpp
>   }
> 
>   if (ospfMyAddressIsRecognizedByNeighbor(pk) == false && ospfNeighborIsRegistered(src) == false) {
> ```

Just minor fixes
```cpp
if (!ospfMyAddressIsRecognizedByNeighbor(pk) && !ospfNeighborIsRegistered(src)) {
```
___
*[`quisp/modules/Common/LinkStateRoutingProtocol/Ospf.cc` line 37 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CXAYNA2qdHgCDrWEU:-N_CXAYNA2qdHgCDrWEV:b7k2nq) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/Common/LinkStateRoutingProtocol/Ospf.cc#L37)):*
> ```cpp
> }
> 
> std::map<NodeAddr, int> LinkStateDatabase::generateRoutingTableFromGraph(NodeAddr src_id) const {
> ```

It would be great if there is brief comments on this as you noted functions above. 
Same as functions below


<!-- Sent from Reviewable.io -->

2023-07-13 07:39 UTC, Tatzhiro reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 2 of 20 files reviewed, 11 unresolved discussions (waiting on @Chibikuri, @Naphann, @Tatzhiro, and @zigen)

___
*[`quisp/modules/Common/Router.h` line 44 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NZ4gFrd8R2vk5DvUexg:-N_D2t3TCA8hnFVarQHd:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/b8341767e39bc54d1b9d0a839e3aa8e529c074f4/quisp/modules/Common/Router.h#L44)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 160 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CLQAK3DRT5PANg5yv:-N_D76R3-XpUpl11SNmI:b-4w11qr) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L160)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Seems `ospfHandleLinkStateUpdate` handling ack packet?
</blockquote></details>

RoutingDaemons do not do anything when they receive Ack.
ospfHandleLinkStateUpdate does not receive ack packets.
It only sends ack packets.
Ack packets are there to mimic the behavior in OSPF.
source: https://tech.pjin.jp/blog/2021/03/31/ospf_5/
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 176 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CQSFO6GtdKaJM5VW4:-N_D98NP43QX2XAyDJ1I:b40g20d) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L176)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Can we combine these statements?

e.g. 
```cpp
if (!ospfMyAddressIsRecognizedByNeighbor(pk) && ospfNeighborIsRegistered(src)) {
   error ()
}else{
 if ...
}
```
</blockquote></details>

Which statements are you taking about?
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 195 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CRGki1RQ9kO_7bIkh:-N_D8IBB4kAbOp_Fa21l:bebrt1w) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L195)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Just minor fixes
```cpp
if (!ospfMyAddressIsRecognizedByNeighbor(pk) && !ospfNeighborIsRegistered(src)) {
```
</blockquote></details>

Will do
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 352 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CO3ug0utszKMaQw8e:-N_D9RCvEOaIsqdAakHZ:b-6ljaud) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L352)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Why the routing table is generated here not in initialization? I haven't looked at it closely, but every time Lsu packet arrives, create a new routing table?
</blockquote></details>

Routing table is not generated in initialization because RoutingDaemon does not have information about topology at initialization. Only when RoutingDaemon updates topology information can it generate a routing table.

Yes, everytime Lsu packet arrives, routing table is updated.
This is because we want to update the routing table in case topology changes for whatever reasons.
___
*[`quisp/test_utils/Channel.h` line 20 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CM0qT-R5J6t8BPbE5:-N_DADoZ3jl61-vdTTGR:bck08vr) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/test_utils/Channel.h#L20)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

You could remove this since we don't care classical cost here?
</blockquote></details>

Yes I can remove this file, but I thought we might use it in the future.
What do you think?
___
*[`quisp/test_utils/Channel.cc` line 8 at r6](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NZ4fQS50qJ5ZRB5dGnD:-N_DAWMjCQPCK8cExNxl:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/b8341767e39bc54d1b9d0a839e3aa8e529c074f4/quisp/test_utils/Channel.cc#L8)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

@zigen @Naphann What do you think? Do we need classical OSPF here? My initial thought was routing cost was a link cost calculated by hardware monitor, but I might be wrong.
</blockquote></details>

Done.
___
*[`quisp/modules/Common/LinkStateRoutingProtocol/Ospf.cc` line 3 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CKilE97-jXBN5k_FP:-N_D2wivBmLcUvmIp1F-:bebrt1w) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/Common/LinkStateRoutingProtocol/Ospf.cc#L3)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

You could move ospf files under routing_daemon/routing_protocols/ or something like that. That would be easy for us to see they are used in routing daemon.
</blockquote></details>

Will do
___
*[`quisp/modules/Common/LinkStateRoutingProtocol/Ospf.cc` line 37 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CXAYNA2qdHgCDrWEU:-N_D6S339tEW62hthvh7:b15sbh5) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/Common/LinkStateRoutingProtocol/Ospf.cc#L37)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

It would be great if there is brief comments on this as you noted functions above. 
Same as functions below
</blockquote></details>

I think this function and other functions are already self explanatory in what it does.
Could you tell me what information is needed in the comments for this function for example?


<!-- Sent from Reviewable.io -->

2023-07-14 02:59 UTC, Chibikuri requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 2 of 20 files reviewed, 12 unresolved discussions (waiting on @Naphann, @Tatzhiro, and @zigen)

___
*[`module_tests/routingdaemon/RoutingDaemon.test` line 25 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_HJK_3DLAp3BN0UwRW:-N_HJK_3DLAp3BN0UwRX:baw98ne) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/module_tests/routingdaemon/RoutingDaemon.test#L25)):*
> ```
>     parameters:
>     @class(TestRoutingDaemon);
>     run_ospf = false;
> ```

I'm not sure, but you might want to use `default(false)` ?
Still, this expression should be fine though...
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 160 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CLQAK3DRT5PANg5yv:-N_HJjXd-ECdGAW6iLOm:b-kixmhy) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L160)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

RoutingDaemons do not do anything when they receive Ack.
ospfHandleLinkStateUpdate does not receive ack packets.
It only sends ack packets.
Ack packets are there to mimic the behavior in OSPF.
source: https://tech.pjin.jp/blog/2021/03/31/ospf_5/
</blockquote></details>

Ah, that made sense to me. Thanks.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 176 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CQSFO6GtdKaJM5VW4:-N_HJzq20QP4pj3kvFPY:b-gapeor) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L176)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

Which statements are you taking about?
</blockquote></details>

The if statement [here](quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc:176) and [here](quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc:183)
___
*[`quisp/test_utils/Channel.h` line 20 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CM0qT-R5J6t8BPbE5:-N_HKHq84KN8RtAZesag:b-1pvmkw) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/test_utils/Channel.h#L20)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

Yes I can remove this file, but I thought we might use it in the future.
What do you think?
</blockquote></details>

Yeah, maybe but maybe not? We can remove it for now and let's remember this when we need this in the future lol.
___
*[`quisp/modules/Common/LinkStateRoutingProtocol/Ospf.cc` line 37 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CXAYNA2qdHgCDrWEU:-N_HIeZt23PepK7YPcza:bzd85qh) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/Common/LinkStateRoutingProtocol/Ospf.cc#L37)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

I think this function and other functions are already self explanatory in what it does.
Could you tell me what information is needed in the comments for this function for example?
</blockquote></details>

I was thinking that when we get doxygen, it would be easy for us to be able to see at least what's input and output. 
But year, you're right. They are fairly easy to understand. So never mind. 


<!-- Sent from Reviewable.io -->

2023-07-16 01:58 UTC, Tatzhiro reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 2 of 20 files reviewed, 12 unresolved discussions (waiting on @Chibikuri, @Naphann, and @zigen)

___
*[`module_tests/routingdaemon/RoutingDaemon.test` line 25 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_HJK_3DLAp3BN0UwRW:-N_M_O_u8vZmW7eX-SA4:b-bkps9x) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/module_tests/routingdaemon/RoutingDaemon.test#L25)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

I'm not sure, but you might want to use `default(false)` ?
Still, this expression should be fine though...
</blockquote></details>

I will change it to default(false)
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 160 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CLQAK3DRT5PANg5yv:-N_McXwtECQYfgXC6lNI:b44tpx) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L160)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Ah, that made sense to me. Thanks.
</blockquote></details>

👍
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 176 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CQSFO6GtdKaJM5VW4:-N_MbTHR8Ax14Bzsjm5i:bul5j0o) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L176)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

The if statement [here](quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc:176) and [here](quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc:183)
</blockquote></details>

I modified the code. Please check if it's the change you wanted.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 195 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CRGki1RQ9kO_7bIkh:-N_Mc_8uATpJcnsDONfq:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L195)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 352 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CO3ug0utszKMaQw8e:-N_MdK5K1hyg97eR4FFD:b-9gigv4) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L352)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

Routing table is not generated in initialization because RoutingDaemon does not have information about topology at initialization. Only when RoutingDaemon updates topology information can it generate a routing table.

Yes, everytime Lsu packet arrives, routing table is updated.
This is because we want to update the routing table in case topology changes for whatever reasons.
</blockquote></details>

Do you still have any problem with this part?
___
*[`quisp/modules/Common/LinkStateRoutingProtocol/Ospf.cc` line 3 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CKilE97-jXBN5k_FP:-N_McTSY1CVkbyIXLTnj:bb6un1j) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/Common/LinkStateRoutingProtocol/Ospf.cc#L3)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done
___
*[`quisp/modules/Common/LinkStateRoutingProtocol/Ospf.cc` line 37 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CXAYNA2qdHgCDrWEU:-N_McUvp0tZdp67KXAKR:b32w1t) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/Common/LinkStateRoutingProtocol/Ospf.cc#L37)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

I was thinking that when we get doxygen, it would be easy for us to be able to see at least what's input and output. 
But year, you're right. They are fairly easy to understand. So never mind. 
</blockquote></details>

Ok
___
*[`quisp/test_utils/Channel.h` line 20 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CM0qT-R5J6t8BPbE5:-N_McPlO7ATOMRLwtoLf:b-uyjvrd) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/test_utils/Channel.h#L20)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Yeah, maybe but maybe not? We can remove it for now and let's remember this when we need this in the future lol.
</blockquote></details>

Ok, I removed it.


<!-- Sent from Reviewable.io -->

2023-07-17 00:53 UTC, Chibikuri requested changes
> Reviewed 5 of 14 files at r7, 5 of 11 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 12 of 20 files reviewed, 8 unresolved discussions (waiting on @Tatzhiro and @zigen)

___
*[`quisp/modules/Common/Router.cc` line 140 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_WCfPi8JAYth_UlNOt:-N_WCfPi8JAYth_UlNOu:b-7l6taa) ([raw file](https://github.com/sfc-aqua/quisp/blob/8e4b4fb369e89f3e22a61e9429546f76b35194d9/quisp/modules/Common/Router.cc#L140)):*
> ```cpp
> 
>   // Check if packet is reachable
>   if (routing_table.count(dest_addr) == false) {
> ```

You could write 
```
if (!routing_table.count(dest_addr)){
...
}
```
or 
```
if(routing_table.count(dest_addr) == 0){
...
}
```
___
*[`quisp/modules/Common/Router.cc` line 154 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_WD6kKDQDcpuoOUf3x:-N_WD6kKDQDcpuoOUf3y:b-ya81ng) ([raw file](https://github.com/sfc-aqua/quisp/blob/8e4b4fb369e89f3e22a61e9429546f76b35194d9/quisp/modules/Common/Router.cc#L154)):*
> ```cpp
> void Router::handleOspfHelloPacket(cMessage *msg) {
>   auto pk = dynamic_cast<OspfHelloPacket *>(msg);
>   if (parentModuleIsQNode() == false) {
> ```

Same as above
___
*[`quisp/modules/Common/Router.cc` line 162 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_WEMAkAapbR_Aq1N_P:-N_WEMAkAapbR_Aq1N_Q:bgvff3m) ([raw file](https://github.com/sfc-aqua/quisp/blob/8e4b4fb369e89f3e22a61e9429546f76b35194d9/quisp/modules/Common/Router.cc#L162)):*
> ```cpp
>     sendOspfHelloPacketToQueue(pk);
>   } else {
>     redirectOspfHelloPacketToRoutingDaemon(pk);
> ```

This name might be confusing? 
In my initial thought, this function forwards a packet to the internal routing daemon, but this function forwards a packet to the next hop routing daemon, right?
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 176 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CQSFO6GtdKaJM5VW4:-N_WFyeD8dpHknxS0wPi:bw7oj5r) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L176)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

I modified the code. Please check if it's the change you wanted.
</blockquote></details>

Yeah, seems fine. 
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 352 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CO3ug0utszKMaQw8e:-N_WJNIm4RTxO6gcS5L3:btrg2zq) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L352)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

Do you still have any problem with this part?
</blockquote></details>

No, it's fine now. Thank you for your explanations.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.ned` line 7 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_WJkUl5XoZiK_ADHim:-N_WJkUl5XoZiK_ADHin:b-32vrgb) ([raw file](https://github.com/sfc-aqua/quisp/blob/8e4b4fb369e89f3e22a61e9429546f76b35194d9/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.ned#L7)):*
> ```
> {
>     parameters:
>         bool run_ospf = default(true);
> ```

Do you want to set a different parameter from what you put in the test file?
module_tests/routingdaemon/RoutingDaemon.test:25


<!-- Sent from Reviewable.io -->

2023-07-18 02:00 UTC, Tatzhiro reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 12 of 20 files reviewed, 8 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[`quisp/modules/Common/Router.cc` line 140 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_WCfPi8JAYth_UlNOt:-N_ahhg-4ohkKgtBZjXv:bb6un1j) ([raw file](https://github.com/sfc-aqua/quisp/blob/8e4b4fb369e89f3e22a61e9429546f76b35194d9/quisp/modules/Common/Router.cc#L140)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

You could write 
```
if (!routing_table.count(dest_addr)){
...
}
```
or 
```
if(routing_table.count(dest_addr) == 0){
...
}
```
</blockquote></details>

Done
___
*[`quisp/modules/Common/Router.cc` line 154 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_WD6kKDQDcpuoOUf3x:-N_ahiYX1uAlwFqi-PgO:bb6un1j) ([raw file](https://github.com/sfc-aqua/quisp/blob/8e4b4fb369e89f3e22a61e9429546f76b35194d9/quisp/modules/Common/Router.cc#L154)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done
___
*[`quisp/modules/Common/Router.cc` line 162 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_WEMAkAapbR_Aq1N_P:-N_agGOl2mM6bQinG61k:bovjafs) ([raw file](https://github.com/sfc-aqua/quisp/blob/8e4b4fb369e89f3e22a61e9429546f76b35194d9/quisp/modules/Common/Router.cc#L162)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

This name might be confusing? 
In my initial thought, this function forwards a packet to the internal routing daemon, but this function forwards a packet to the next hop routing daemon, right?
</blockquote></details>

No, this function fowards a packet to the internal routing daemon.
I added a variable to make the intent more obvious.
Is it better now?
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 176 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CQSFO6GtdKaJM5VW4:-N_ahkl34p6EHbs6YHgS:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L176)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Yeah, seems fine. 
</blockquote></details>

Done.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 352 at r7](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_CO3ug0utszKMaQw8e:-N_ahn4VD-UcNwYS3qWu:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/1bdddd277cdb78f47954de7550af9c247e36b497/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L352)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

No, it's fine now. Thank you for your explanations.
</blockquote></details>

Done.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.ned` line 7 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_WJkUl5XoZiK_ADHim:-N_ahnwx8USBrVrkttqh:b-bq1qzl) ([raw file](https://github.com/sfc-aqua/quisp/blob/8e4b4fb369e89f3e22a61e9429546f76b35194d9/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.ned#L7)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Do you want to set a different parameter from what you put in the test file?
module_tests/routingdaemon/RoutingDaemon.test:25
</blockquote></details>

In the module test, the code is testing the omnet++ topology generation.
That means we do not want to run our ospf.
For other parts of the code, we want to run ospf by default.

That is why I set different parameter in the module test.


<!-- Sent from Reviewable.io -->

2023-07-18 02:20 UTC, Chibikuri requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 12 of 20 files reviewed, 4 unresolved discussions (waiting on @Tatzhiro and @zigen)

___
*[`quisp/modules/Common/Router.cc` line 162 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_WEMAkAapbR_Aq1N_P:-N_akFPl8Ct0JG3-nJ9z:bi9hoti) ([raw file](https://github.com/sfc-aqua/quisp/blob/8e4b4fb369e89f3e22a61e9429546f76b35194d9/quisp/modules/Common/Router.cc#L162)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

No, this function fowards a packet to the internal routing daemon.
I added a variable to make the intent more obvious.
Is it better now?
</blockquote></details>

So when the source node is the node itself, why do we need to put the hello packet to queue again? Can't we just drop the packet?
 
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.ned` line 7 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_WJkUl5XoZiK_ADHim:-N_amxb89geno7iLIOlm:b-kokj4l) ([raw file](https://github.com/sfc-aqua/quisp/blob/8e4b4fb369e89f3e22a61e9429546f76b35194d9/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.ned#L7)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

In the module test, the code is testing the omnet++ topology generation.
That means we do not want to run our ospf.
For other parts of the code, we want to run ospf by default.

That is why I set different parameter in the module test.
</blockquote></details>

I see. Thank you for your explanation.


<!-- Sent from Reviewable.io -->

2023-07-18 02:47 UTC, Tatzhiro reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 12 of 20 files reviewed, 4 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[`quisp/modules/Common/Router.cc` line 162 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_WEMAkAapbR_Aq1N_P:-N_arCOY0Zf5zkEnE5v7:b-r9f4q4) ([raw file](https://github.com/sfc-aqua/quisp/blob/8e4b4fb369e89f3e22a61e9429546f76b35194d9/quisp/modules/Common/Router.cc#L162)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

So when the source node is the node itself, why do we need to put the hello packet to queue again? Can't we just drop the packet?
 
</blockquote></details>

When the source node is the node itself, the packet has gone through ↓
1. packet created by Node1 RoutingDaemon
2. packet sent to Node1 Router
which means at step 2, it has not gone through queue yet.

The subsequent step is ↓
3. packet sent to Node1 Queue
4. packet arrives to Node2 Queue
5. packet arrives to Node2 Router
6. packet redirected to Node2 RoutingDaemon

Therefore, when the source node is the node itself, it means that the packet is supposed to be sent to neighboring nodes.
You may think why not use pk->getDestAddr() instead.
At initialization, RoutingDaemon sends packets to neighbors without the information of destination address.
So, I am using source address to identify whether the packet is supposed to be sent to other nodes, or redirected to self node.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.ned` line 7 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_WJkUl5XoZiK_ADHim:-N_arB_2BoaHZIUd26kv:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/8e4b4fb369e89f3e22a61e9429546f76b35194d9/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.ned#L7)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

I see. Thank you for your explanation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-18 04:00 UTC, Chibikuri approved these changes
I ran a simulation and verified the routing table is properly generated. 
Thanks tatsu!
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526#-:-N_b8nehD8bmvV92tTs9:bw4ez3e)* status: 12 of 20 files reviewed, 3 unresolved discussions (waiting on @Tatzhiro and @zigen)

___
*[`quisp/modules/Common/Router.cc` line 162 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_WEMAkAapbR_Aq1N_P:-N_auedOD7DcdB2U2PKi:b-wk43yc) ([raw file](https://github.com/sfc-aqua/quisp/blob/8e4b4fb369e89f3e22a61e9429546f76b35194d9/quisp/modules/Common/Router.cc#L162)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

When the source node is the node itself, the packet has gone through ↓
1. packet created by Node1 RoutingDaemon
2. packet sent to Node1 Router
which means at step 2, it has not gone through queue yet.

The subsequent step is ↓
3. packet sent to Node1 Queue
4. packet arrives to Node2 Queue
5. packet arrives to Node2 Router
6. packet redirected to Node2 RoutingDaemon

Therefore, when the source node is the node itself, it means that the packet is supposed to be sent to neighboring nodes.
You may think why not use pk->getDestAddr() instead.
At initialization, RoutingDaemon sends packets to neighbors without the information of destination address.
So, I am using source address to identify whether the packet is supposed to be sent to other nodes, or redirected to self node.
</blockquote></details>

Ah, that makes sense to me. Thanks.


<!-- Sent from Reviewable.io -->

2023-07-18 04:55 UTC, Tatzhiro reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 12 of 20 files reviewed, 3 unresolved discussions (waiting on @Chibikuri and @zigen)

___
*[`quisp/modules/Common/Router.cc` line 162 at r8](https://reviewable.io/reviews/sfc-aqua/quisp/526#-N_WEMAkAapbR_Aq1N_P:-N_bLbW4-FLk923g0J8h:b-896fix) ([raw file](https://github.com/sfc-aqua/quisp/blob/8e4b4fb369e89f3e22a61e9429546f76b35194d9/quisp/modules/Common/Router.cc#L162)):*
<details><summary><i>Previously, Chibikuri (Ryosuke Satoh (cocori)) wrote…</i></summary><blockquote>

Ah, that makes sense to me. Thanks.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-18 04:57 UTC, Tatzhiro reviewed
> Dismissed @zigen from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 12 of 20 files reviewed, 1 unresolved discussion (waiting on @Chibikuri and @zigen)



<!-- Sent from Reviewable.io -->

2023-07-18 04:58 UTC, Tatzhiro reviewed
> Dismissed @Chibikuri from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 12 of 20 files reviewed, all discussions resolved (waiting on @zigen)



<!-- Sent from Reviewable.io -->

2023-07-28 09:35 UTC, zigen requested changes
> Reviewed 1 of 7 files at r6, 2 of 14 files at r7, 2 of 11 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 15 of 20 files reviewed, 4 unresolved discussions (waiting on @Chibikuri and @Tatzhiro)

___
*[`quisp/messages/ospf_messages.msg` line 63 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NaQpkSO1BfKhTSSD8ll:-NaQpkSO1BfKhTSSD8lm:b-682p6p) ([raw file](https://github.com/sfc-aqua/quisp/blob/c717bd0786581f8038d1deb4ed2e41a85cec1a83/quisp/messages/ospf_messages.msg#L63)):*
> ```
> {
>     OspfState state;
>     bool is_master;
> ```

use camelCase for fields in messages.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.h` line 59 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NaQqI0Z7Naa0wIThWzZ:-NaQqI0Z7Naa0wIThWz_:b-exx6k1) ([raw file](https://github.com/sfc-aqua/quisp/blob/c717bd0786581f8038d1deb4ed2e41a85cec1a83/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.h#L59)):*
> ```objc
>   void ospfExStartState(const OspfDbdPacket *const pk);
>   void ospfSendExstartDbdPacket(NodeAddr neighbor);
>   void ospfSlaveInitiateExchangeState(int dest);
> ```

does the argument `dest` have the type `NodeAddr`, not `int` right?
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 239 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NaQoPjW-QC6PROvai_e:-NaQoPjXC-eBIi20h0ge:bt18boh) ([raw file](https://github.com/sfc-aqua/quisp/blob/c717bd0786581f8038d1deb4ed2e41a85cec1a83/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L239)):*
> ```cpp
>   if (pk->getState() == OspfState::EXSTART) {
>     return ospfExStartState(pk);
>   } else if (pk->getState() == OspfState::EXCHANGE) {
> ```

you don't need to use `else`.

```cpp
  return;
}

if (pk->getState() == OspfState::EXCHANGE) {
```



_Code quote:_
```cpp
 } else if (pk->getState() == OspfState::EXCHANGE) {
```
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 242 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NaQoplk1DT59WVIZNHk:-NaQoplk1DT59WVIZNHl:b-warz9e) ([raw file](https://github.com/sfc-aqua/quisp/blob/c717bd0786581f8038d1deb4ed2e41a85cec1a83/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L242)):*
> ```cpp
>     const int src = pk->getSrcAddr();
> 
>     if (bool i_am_master = (!pk->getIs_master())) {
> ```

do we need this variable? and assign it in the condition clause?
how about this?

```cpp
    if (!pk->getIs_master()) {
```


<!-- Sent from Reviewable.io -->

2023-07-31 09:58 UTC, Tatzhiro reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 14 of 20 files reviewed, 4 unresolved discussions (waiting on @zigen)

___
*[`quisp/messages/ospf_messages.msg` line 63 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NaQpkSO1BfKhTSSD8ll:-NafF_rBAyoLdYxUKSjG:b7918d0) ([raw file](https://github.com/sfc-aqua/quisp/blob/c717bd0786581f8038d1deb4ed2e41a85cec1a83/quisp/messages/ospf_messages.msg#L63)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

use camelCase for fields in messages.
</blockquote></details>

Most of other messages in other files have snake-case member variable names.
Should I still use camelCase?
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.h` line 59 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NaQqI0Z7Naa0wIThWzZ:-NafFlsT7pl1GrxyWotw:bpinm6a) ([raw file](https://github.com/sfc-aqua/quisp/blob/c717bd0786581f8038d1deb4ed2e41a85cec1a83/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.h#L59)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

does the argument `dest` have the type `NodeAddr`, not `int` right?
</blockquote></details>

You are right, I changed ints to NodeAddr type accordingly.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 239 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NaQoPjW-QC6PROvai_e:-NafI3sY-lh0MZAU16LI:b-so8a54) ([raw file](https://github.com/sfc-aqua/quisp/blob/c717bd0786581f8038d1deb4ed2e41a85cec1a83/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L239)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

you don't need to use `else`.

```cpp
  return;
}

if (pk->getState() == OspfState::EXCHANGE) {
```
</blockquote></details>

Ok.
I will change it to checking abonormal state.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 242 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NaQoplk1DT59WVIZNHk:-NafKj_y-wWTtA2BglJ7:b-p0k1pe) ([raw file](https://github.com/sfc-aqua/quisp/blob/c717bd0786581f8038d1deb4ed2e41a85cec1a83/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L242)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

do we need this variable? and assign it in the condition clause?
how about this?

```cpp
    if (!pk->getIs_master()) {
```
</blockquote></details>

I used the variable to make it clear that I am checking whether 'this' node is the master or not.
I thought ones might get confused from`!pk->getIs\_master()` because it doesnt tell if `is_master` is suggesting this node or the packet source node.
If you think it's unnecessary I will delete it.
What do you think?


<!-- Sent from Reviewable.io -->

2023-08-01 04:21 UTC, zigen requested changes
> Reviewed 2 of 11 files at r8, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 18 of 20 files reviewed, 3 unresolved discussions (waiting on @Chibikuri, @getter, and @Tatzhiro)

___
*[`quisp/messages/ospf_messages.msg` line 63 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NaQpkSO1BfKhTSSD8ll:-NajJGhkAp_lb1VYY5fG:b-6owe3n) ([raw file](https://github.com/sfc-aqua/quisp/blob/c717bd0786581f8038d1deb4ed2e41a85cec1a83/quisp/messages/ospf_messages.msg#L63)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

Most of other messages in other files have snake-case member variable names.
Should I still use camelCase?
</blockquote></details>

.msg files is used for generating _m.cc files, and the snake case name will be the mixed case name like `getIs_master`.
to avoid this, use the camelCase or use @getter and @setter like this
https://github.com/sfc-aqua/quisp/blob/master/quisp/messages/QNode_ipc_messages.msg#L15

maybe `@getter(isMaster)` `@setter(setMaster)` seems better.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 242 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NaQoplk1DT59WVIZNHk:-NajIcE4DHXn_jhj2PHg:b-t3qfl6) ([raw file](https://github.com/sfc-aqua/quisp/blob/c717bd0786581f8038d1deb4ed2e41a85cec1a83/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L242)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

I used the variable to make it clear that I am checking whether 'this' node is the master or not.
I thought ones might get confused from`!pk->getIs\_master()` because it doesnt tell if `is_master` is suggesting this node or the packet source node.
If you think it's unnecessary I will delete it.
What do you think?
</blockquote></details>

I see, it's necessary. but I think this causes unused variable warning, so you should put a comment to clarify it.


<!-- Sent from Reviewable.io -->

2023-08-02 07:16 UTC, Tatzhiro reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 13 of 20 files reviewed, 3 unresolved discussions (waiting on @Chibikuri, @getter, and @zigen)

___
*[`quisp/messages/ospf_messages.msg` line 63 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NaQpkSO1BfKhTSSD8ll:-Nap2uwe2aIdjoeBtj-s:bw7wxc0) ([raw file](https://github.com/sfc-aqua/quisp/blob/c717bd0786581f8038d1deb4ed2e41a85cec1a83/quisp/messages/ospf_messages.msg#L63)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

.msg files is used for generating _m.cc files, and the snake case name will be the mixed case name like `getIs_master`.
to avoid this, use the camelCase or use @getter and @setter like this
https://github.com/sfc-aqua/quisp/blob/master/quisp/messages/QNode_ipc_messages.msg#L15

maybe `@getter(isMaster)` `@setter(setMaster)` seems better.
</blockquote></details>

Thanks for the suggestion.
`@getter()` `@setter()` serves to be perfect here.
I changed all the getters and setters acoordingly.
___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 242 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NaQoplk1DT59WVIZNHk:-Nap36rWEolYS3hiFfzl:bdv5y17) ([raw file](https://github.com/sfc-aqua/quisp/blob/c717bd0786581f8038d1deb4ed2e41a85cec1a83/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L242)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

I see, it's necessary. but I think this causes unused variable warning, so you should put a comment to clarify it.
</blockquote></details>

On my machine, it did not cause any warning in RoutingDaemon.cc file.
However, if it causes any warnings on your machine or other environments, I will change it to the following:
```C++
bool i_am_master = !pk->isMaster(); 
if (i_am_master) {     
    ospfMasterEnterExchangeState(src); 
}
```
Did you experience any warnings?


<!-- Sent from Reviewable.io -->

2023-08-03 01:27 UTC, zigen requested changes
> Reviewed 2 of 11 files at r8, 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: all files reviewed, 1 unresolved discussion (waiting on @Tatzhiro)

___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 242 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NaQoplk1DT59WVIZNHk:-Nat-AcU7uEcXo5mj9q4:b-7u5c61) ([raw file](https://github.com/sfc-aqua/quisp/blob/c717bd0786581f8038d1deb4ed2e41a85cec1a83/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L242)):*
<details><summary><i>Previously, Tatzhiro wrote…</i></summary><blockquote>

On my machine, it did not cause any warning in RoutingDaemon.cc file.
However, if it causes any warnings on your machine or other environments, I will change it to the following:
```C++
bool i_am_master = !pk->isMaster(); 
if (i_am_master) {     
    ospfMasterEnterExchangeState(src); 
}
```
Did you experience any warnings?
</blockquote></details>

that seems fine. 


<!-- Sent from Reviewable.io -->

2023-08-03 13:01 UTC, Tatzhiro reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @zigen)

___
*[`quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc` line 242 at r9](https://reviewable.io/reviews/sfc-aqua/quisp/526#-NaQoplk1DT59WVIZNHk:-NavUJu5ExGHyfQSKfaE:bb6un1j) ([raw file](https://github.com/sfc-aqua/quisp/blob/c717bd0786581f8038d1deb4ed2e41a85cec1a83/quisp/modules/QRSA/RoutingDaemon/RoutingDaemon.cc#L242)):*
<details><summary><i>Previously, zigen (Kentaro "zigen" Teramoto) wrote…</i></summary><blockquote>

that seems fine. 
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-08-06 12:18 UTC, zigen approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526#-:-Nb9m7dIAzXoMcYXlazq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Tatzhiro)



<!-- Sent from Reviewable.io -->

2023-08-07 03:00 UTC, Tatzhiro reviewed
@Chibikuri @zigen @Naphann Thank you so much for your reviews and advice!

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/526#-:-NbCvkooDWU6aazlYb8L:b-4549wb)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Tatzhiro)



<!-- Sent from Reviewable.io -->

2023-08-07 03:00 UTC, merged