release back to pool on photon discard event
sfc-aqua/quisp pull request #531
Opened 2023-07-17 07:36 UTC by res6idue

This PR fixes the issue that the memory gets used up, resulting in a kill.

2023-07-17 15:59 UTC, Naphann requested changes
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/531)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @res6idue and @zigen)

___
*[`quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc` line 178 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/531#-N_ZZqI53KdvR5q-3ruD:-N_ZZqI53KdvR5q-3ruE:b9ol9wz) ([raw file](https://github.com/sfc-aqua/quisp/blob/7c9a55eecc7aaaa8a751cb377e239faba9289233/quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc#L178)):*
> ```cpp
> }
> 
> void BellStateAnalyzer::measureSuccessfully(PhotonRecord &p, PhotonRecord &q, bool is_psi_plus) {
> ```

If discard photon function doesn't return photonic qubits to pool properly. What about this one? Have you checked this case?


<!-- Sent from Reviewable.io -->

2023-07-18 00:39 UTC, res6idue reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/531)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Naphann and @zigen)

___
*[`quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc` line 178 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/531#-N_ZZqI53KdvR5q-3ruD:-N_aPz5BE6zbIB8l7oWC:b7herxb) ([raw file](https://github.com/sfc-aqua/quisp/blob/7c9a55eecc7aaaa8a751cb377e239faba9289233/quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc#L178)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

If discard photon function doesn't return photonic qubits to pool properly. What about this one? Have you checked this case?
</blockquote></details>

I think for the case when we hit this function, we still arrive at discard photons
Well I think that when we fail in the indistinguishable window, we also need to discard those photons, so I will fix it.


<!-- Sent from Reviewable.io -->

2023-08-04 15:53 UTC, res6idue reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/531)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Chibikuri, @Naphann, and @zigen)

___
*[`quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc` line 178 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/531#-N_ZZqI53KdvR5q-3ruD:-Nb0FAKf8tICGPjItQi0:bt2vr1b) ([raw file](https://github.com/sfc-aqua/quisp/blob/7c9a55eecc7aaaa8a751cb377e239faba9289233/quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc#L178)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

I think for the case when we hit this function, we still arrive at discard photons
Well I think that when we fail in the indistinguishable window, we also need to discard those photons, so I will fix it.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2023-08-20 18:01 UTC, Naphann requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/531)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Chibikuri, @res6idue, and @zigen)

___
*[`quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc` line 178 at r1](https://reviewable.io/reviews/sfc-aqua/quisp/531#-N_ZZqI53KdvR5q-3ruD:-NcJ5jTt9s-pf8znF_qV:b-3wx6g1) ([raw file](https://github.com/sfc-aqua/quisp/blob/7c9a55eecc7aaaa8a751cb377e239faba9289233/quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc#L178)):*
<details><summary><i>Previously, res6idue (soon) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

See my other comment. 
___
*[`quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc` line 102 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/531#-NcJ5md70vy6tqqd3b91:-NcJ5md70vy6tqqd3b92:brq2ytg) ([raw file](https://github.com/sfc-aqua/quisp/blob/2d5e0faffa62831f094f73432834963e24948f59/quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc#L102)):*
> ```cpp
>     auto q = second_port_records[i];
> 
>     if (fabs(p.arrival_time - q.arrival_time) < indistinguishability_window) {
> ```

What about this case? Do they get returned to the pool properly somewhere?


<!-- Sent from Reviewable.io -->

2023-08-21 05:04 UTC, res6idue reviewed
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/531)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Chibikuri, @Naphann, and @zigen)

___
*[`quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc` line 102 at r2](https://reviewable.io/reviews/sfc-aqua/quisp/531#-NcJ5md70vy6tqqd3b91:-NcLTD362vahghlYMbbR:b-lcanyb) ([raw file](https://github.com/sfc-aqua/quisp/blob/2d5e0faffa62831f094f73432834963e24948f59/quisp/modules/PhysicalConnection/BSA/BellStateAnalyzer.cc#L102)):*
<details><summary><i>Previously, Naphann (Naphan Benchasattabuse) wrote…</i></summary><blockquote>

What about this case? Do they get returned to the pool properly somewhere?
</blockquote></details>

sorry, I forgot to add the discard photon function for the successful case.


<!-- Sent from Reviewable.io -->

2023-10-17 06:18 UTC, Naphann approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/531)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri and @zigen)



<!-- Sent from Reviewable.io -->

2023-10-17 09:38 UTC, zigen approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/531#-:-Ngx-0DIEO6IxRVUWh1_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)



<!-- Sent from Reviewable.io -->

2023-10-17 10:47 UTC, Naphann reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/sfc-aqua/quisp/531#-:-NgxEuQvCeCuPI4IsFm_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Chibikuri)



<!-- Sent from Reviewable.io -->

2023-10-17 11:55 UTC, merged